### PR TITLE
PG-1408: Prevent detection of omissible "he said" reference block when there is additional following text

### PR DESCRIPTION
**Pull request by tombogle**
PG-1408 [Part 1]: Prevent detection of omissible "he said" reference block when there is additional following text.
Also, improve block matchup logic to assign narrator to the correlated block when the vernacular text starts with an apparent dialogue closing dash.

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/glyssen/729)

### CODE REVIEW

**Review by andrew-polk — COMMENTED** [review]
> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/glyssen/729)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by andrew-polk — COMMENTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/glyssen/729)* status: all files reviewed, 1 unresolved discussion (waiting on @tombogle)

___
*[GlyssenEngine/ReferenceText.cs, line 687 at r2](https://reviewable.io/reviews/sillsdev/glyssen/729#-MK1D5U6C8fk3bBE8FgT:-MK1D5U6C8fk3bBE8FgU:b-w0bgs8) ([raw file](https://github.com/sillsdev/glyssen/blob/630edfee125d16271c436ba7c01ab59da5a8580a/GlyssenEngine/ReferenceText.cs#L687)):*
> ```
> // TODO: This needs to be UNmatched:
> ```
Is this still forthcoming?

**Review by andrew-polk — COMMENTED** [review]
> Reviewed 5 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/glyssen/729)* status: all files reviewed, 1 unresolved discussion (waiting on @tombogle)

___
*[GlyssenEngine/ReferenceText.cs, line 687 at r3](https://reviewable.io/reviews/sillsdev/glyssen/729#-MKGJoQV66mh6I5-CJUs:-MKGJoQV66mh6I5-CJUt:b-vdhqpv) ([raw file](https://github.com/sillsdev/glyssen/blob/e9ad7d81866d3722605887c2c4eda24c4666c68e/GlyssenEngine/ReferenceText.cs#L687)):*
> ```
> Since modifiedOmittedHeSaidText is always the English one
> ```
I think this comment needs to be updated.

**Review by andrew-polk — COMMENTED** [review]
> Reviewed 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/glyssen/729)* status: all files reviewed, 1 unresolved discussion (waiting on @tombogle)

**Review by tombogle — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/glyssen/729)* status: 7 of 9 files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[GlyssenEngine/ReferenceText.cs, line 687 at r3](https://reviewable.io/reviews/sillsdev/glyssen/729#-MKGJoQV66mh6I5-CJUs:-MKauRhTDYTvnnjdCRIt:b-896fix) ([raw file](https://github.com/sillsdev/glyssen/blob/e9ad7d81866d3722605887c2c4eda24c4666c68e/GlyssenEngine/ReferenceText.cs#L687)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> Since modifiedOmittedHeSaidText is always the English one
> ```
I think this comment needs to be updated.
</blockquote></details>

Done.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/glyssen/729)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by andrew-polk — APPROVED** [review]
I won't pretend my approval means I think the logic is correct; too complicated for that. 
So if you want me to review it for correctness, you'll have to walk me through it.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/glyssen/729#-:-MKazLjg9EalOs62Fs04:b2rztf8)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
