### PR TITLE
Prep for new ParatextData.dll and new version of libpalaso with…

### PR DESCRIPTION
**Pull request by tombogle**
… breaking VerseRef changes.

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/glyssen/456)

### CODE REVIEW

**Comment by tombogle** [comment]
___
*[Glyssen/MainForm.cs, line 29 at r1](https://reviewable.io/reviews/sillsdev/glyssen/456#-LKOS0Bq3wp-5VM6LKCQ:-LKhFOhQC1AyuCdg2gJ3:b6ycsqt) ([raw file](https://github.com/sillsdev/glyssen/blob/5dd7a0d72385545294a682825f5db30858acf5d3/Glyssen/MainForm.cs#L29)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Why does removing a line necessitate a new using statement?
</blockquote></details>

InvalidVersificationLineException used to be defined in ParatextData, but it was moved to SIL.Scripture

**Comment by andrew-polk** [comment]
Don't merge. This has run-time issues.

**Comment by tombogle** [comment]
Your changes look okay. I was a little surprised and disappointed to see that the new entries were needed for DotNetZip in the app.config files.

**Comment by andrew-polk** [comment]
> I was a little surprised and disappointed to see that the new entries were needed for DotNetZip in the app.config files.

I had to upgrade versions of DotNetZip. I think maybe libpalaso or ParatextData was looking for a particular version? Anyway, when I did the upgrade via NuGet, it automatically made the changes to app.config.

**Pull request merged**
