### PR TITLE
PG-673: Show alert if more narrators than actors

### PR DESCRIPTION
**Pull request by phillip-hopper**
If cast size has fewer adult actors of a particular gender than required for the selected narrator preferences, user should be alerted.

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/glyssen/133)

### CODE REVIEW

**Comment by andrew-polk** [comment]
Reviewed 1 of 2 files at r1.
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[Glyssen/Dialogs/CastSizePlanningDlg.cs, line 232 \[r1\]](https://reviewable.io:443/reviews/sillsdev/glyssen/133#-KFiR9DI-PWh52a7mhtX:-KFiR9DJC-6ITr_UzSxZ:899740533) ([raw file](https://github.com/sillsdev/glyssen/blob/ed7064ae5b5a2b75ab3c598962d3783dcc8525f4/Glyssen/Dialogs/CastSizePlanningDlg.cs#L232)):*
I think we need to call ShowOrHideNarratorCountWarning here.

---

*[Glyssen/Dialogs/CastSizePlanningDlg.cs, line 241 \[r1\]](https://reviewable.io:443/reviews/sillsdev/glyssen/133#-KFiR7rSTSbLuu7w69R_:-KFiR7rSTSbLuu7w69Ra:899740533) ([raw file](https://github.com/sillsdev/glyssen/blob/ed7064ae5b5a2b75ab3c598962d3783dcc8525f4/Glyssen/Dialogs/CastSizePlanningDlg.cs#L241)):*
I think we need to call ShowOrHideNarratorCountWarning here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/glyssen/133)*

**Comment by andrew-polk** [comment]
Reviewed 1 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/glyssen/133)*

**Comment by phillip-hopper** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[Glyssen/Dialogs/CastSizePlanningDlg.cs, line 232 \[r1\]](https://reviewable.io:443/reviews/sillsdev/glyssen/133#-KFiR9DI-PWh52a7mhtX:-KFikQXek2HcpcAU2A-6:-499146009) ([raw file](https://github.com/sillsdev/glyssen/blob/ed7064ae5b5a2b75ab3c598962d3783dcc8525f4/Glyssen/Dialogs/CastSizePlanningDlg.cs#L232)):*
Done.

---

*[Glyssen/Dialogs/CastSizePlanningDlg.cs, line 241 \[r1\]](https://reviewable.io:443/reviews/sillsdev/glyssen/133#-KFiR7rSTSbLuu7w69R_:-KFikQtiKNKFtdfBWghn:-499146009) ([raw file](https://github.com/sillsdev/glyssen/blob/ed7064ae5b5a2b75ab3c598962d3783dcc8525f4/Glyssen/Dialogs/CastSizePlanningDlg.cs#L241)):*
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/glyssen/133)*

**Comment by andrew-polk** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/glyssen/133)*

**Comment by andrew-polk** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/glyssen/133#-:-KFkLrhx-3ZMRd626Oxj:1417088721)*

**Pull request merged**
