### PR TITLE
PG-1404: Prevent crash switching to Select Character mode when matchup's first block is not relevant

### PR DESCRIPTION
**Pull request by tombogle**
Note: this might also solve PG-1403

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/glyssen/723)

### CODE REVIEW

**Review by andrew-polk — APPROVED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/glyssen/723)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by andrew-polk — COMMENTED** [review]
> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/glyssen/723)* status: all files reviewed, 1 unresolved discussion (waiting on @tombogle)

___
*[GlyssenEngine/Script/Block.cs, line 387 at r2](https://reviewable.io/reviews/sillsdev/glyssen/723#-MGp0e_XAsjo1Q0O048M:-MGp0e_XAsjo1Q0O048N:b-etxij1) ([raw file](https://github.com/sillsdev/glyssen/blob/c72b39f0064c1096e97d2d57ce5331212dc6234e/GlyssenEngine/Script/Block.cs#L387)):*
> ```
> CharacterId = CharacterVerseData.GetStandardCharacterId(BCVRef.NumberToBookCode(bookNum), CharacterVerseData.StandardCharacter.Narrator);
> ```
This is an unexpected side-effect of calling a Try... method.
Probably should at least document it.

**Review by tombogle — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/glyssen/723)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[GlyssenEngine/Script/Block.cs, line 387 at r2](https://reviewable.io/reviews/sillsdev/glyssen/723#-MGp0e_XAsjo1Q0O048M:-MGs5N_r8qqM6j8wV2uB:b-896fix) ([raw file](https://github.com/sillsdev/glyssen/blob/c72b39f0064c1096e97d2d57ce5331212dc6234e/GlyssenEngine/Script/Block.cs#L387)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> CharacterId = CharacterVerseData.GetStandardCharacterId(BCVRef.NumberToBookCode(bookNum), CharacterVerseData.StandardCharacter.Narrator);
> ```
This is an unexpected side-effect of calling a Try... method.
Probably should at least document it.
</blockquote></details>

Done.

**Comment by tombogle** [comment]
I now doubt that PG-1404 is related to PG-1403, so the branch on which this PR is based is poorly named, but this does fix a real issue, so I think it's ready to be merged if it can get a final approval.

**Review by andrew-polk — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/glyssen/723)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by andrew-polk — COMMENTED** [review]
> Reviewed 5 of 5 files at r4.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/glyssen/723)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by andrew-polk — APPROVED** [review]
> Reviewed 3 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/glyssen/723)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
