### PR TITLE
Added analytics event for glyssenscript exports

### PR DESCRIPTION
**Pull request by tombogle**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/glyssen/839)

### CODE REVIEW

**Review by andrew-polk — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/glyssen/839)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @bryanwussow)

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/glyssen/839)* status: all files reviewed, 1 unresolved discussion (waiting on @bryanwussow and @tombogle)

___
*[`Glyssen/Dialogs/ExportToRecordingToolDlg.cs` line 67 at r1](https://reviewable.io/reviews/sillsdev/glyssen/839#-NGSSEZoEvwdvEslwBgK:-NGSSEZoEvwdvEslwBgL:b3n6ljx) ([raw file](https://github.com/sillsdev/glyssen/blob/dbe282c50e03f3ed9f3b2c808bb31c2031e31ef9/Glyssen/Dialogs/ExportToRecordingToolDlg.cs#L67)):*
> ```Smalltalk
> 					{ "includeVoiceActors", m_viewModel.IncludeVoiceActors.ToString() },
> 					{ "includeDelivery", m_viewModel.IncludeDelivery.ToString() }
> 				});
> ```

Would it be better to do the analytics event after making the file in case it (either one, I guess) throws?

**Comment by tombogle** [comment]
*[`Glyssen/Dialogs/ExportToRecordingToolDlg.cs` line 67 at r1](https://reviewable.io/reviews/sillsdev/glyssen/839#-NGSSEZoEvwdvEslwBgK:-NGSefWlCmHOZYeSpAIq:bq6jdzr) ([raw file](https://github.com/sillsdev/glyssen/blob/dbe282c50e03f3ed9f3b2c808bb31c2031e31ef9/Glyssen/Dialogs/ExportToRecordingToolDlg.cs#L67)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Would it be better to do the analytics event after making the file in case it (either one, I guess) throws?
</blockquote></details>

Probably not. I think what we really want to know is that someone *wanted* to export. If they tried and failed, it's still probably worth counting. Anyway, I would hope that failures should be rare enough as to not have a major effect on the totals.

**Review by bryanwussow — COMMENTED** [review]
Looks good. Thank you.

**Review by andrew-polk — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/glyssen/839)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tombogle)

**Pull request merged**
