### PR TITLE
Removed DesktopAnalytics and all other UI from Project.cs

### PR DESCRIPTION
**Pull request by AndrewChristensenFCBH**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/glyssen/588)

### CODE REVIEW

**Comment by tombogle** [comment]
___
*[Glyssen/Program.cs, line 8 at r1](https://reviewable.io/reviews/sillsdev/glyssen/588#-LxveKpv9ydAR4QWV1rW:-LxveKpv9ydAR4QWV1rX:buonpeb) ([raw file](https://github.com/sillsdev/glyssen/blob/939d5e623efb59dd2c77dbea9c2f05d6c8f5df16/Glyssen/Program.cs#L8)):*
> ```Smalltalk
> using System.Linq;
> using System.Windows.Forms;
> using DesktopAnalytics;
> ```

Is this using still needed? Looks like you're now having to make this explicit.

**Comment by tombogle** [comment]
___
*[Glyssen/DataMigrator.cs, line 32 at r1](https://reviewable.io/reviews/sillsdev/glyssen/588#-LxvfOhaD4wDrc3HeDcX:-LxvfOhb9EYxDET9jLlX:b-zgoiz1) ([raw file](https://github.com/sillsdev/glyssen/blob/939d5e623efb59dd2c77dbea9c2f05d6c8f5df16/Glyssen/DataMigrator.cs#L32)):*
> ```Smalltalk
> 		}
> 
> 		private static bool UpgradeToCurrentDataFormatVersion(ApplicationMetadata info, Func<string, string, bool> confirmAndRecycleAction, out string warning)
> ```

I see you've added two new parameters here, but other than setting the warning string to null, they don't seem to be used. Did you forget something?

**Comment by tombogle** [comment]
___
*[Glyssen/DataMigrator.cs, line 34 at r1](https://reviewable.io/reviews/sillsdev/glyssen/588#-LxvfkVr2hAIaOdQJgQl:-LxvfkVr2hAIaOdQJgQm:b-ge5mj8) ([raw file](https://github.com/sillsdev/glyssen/blob/939d5e623efb59dd2c77dbea9c2f05d6c8f5df16/Glyssen/DataMigrator.cs#L34)):*
> ```Smalltalk
> 		private static bool UpgradeToCurrentDataFormatVersion(ApplicationMetadata info, Func<string, string, bool> confirmAndRecycleAction, out string warning)
> 		{
> 			warning = null;
> ```

What is this warning parameter for? It only ever gets set to null.

**Comment by tombogle** [comment]
___
*[Glyssen/DataMigrator.cs, line 111 at r1](https://reviewable.io/reviews/sillsdev/glyssen/588#-LxvgWg1-xx1AZZGwnOI:-LxvgWg1-xx1AZZGwnOJ:bjycapo) ([raw file](https://github.com/sillsdev/glyssen/blob/939d5e623efb59dd2c77dbea9c2f05d6c8f5df16/Glyssen/DataMigrator.cs#L111)):*
> ```Smalltalk
> 										// so for this step in the migration process (going from 0 to 1), any project without
> 										// OriginalReleaseBundlePath set is invalid (possibly from a really early version of Glyssen
> 										// or some g;itch arising from development activity or external mangling of the file). So
> ```

If you make other changes to this file, please fix this typo.

**Comment by tombogle** [comment]
___
*[Glyssen/Project.cs, line 1249 at r1](https://reviewable.io/reviews/sillsdev/glyssen/588#-Lxvj5JHDhC-2BxNxtMM:-Lxvj5JI387tz-XoL18W:bi7ex4y) ([raw file](https://github.com/sillsdev/glyssen/blob/939d5e623efb59dd2c77dbea9c2f05d6c8f5df16/Glyssen/Project.cs#L1249)):*
> ```Smalltalk
> 		}
> 
> 		public static void DeleteProjectFolderAndEmptyContainingFolders(string projectFolder, Func<string, string, bool> confirmAndRecycleAction = null)
> ```

With only two callers and one of them never passing in a confirmAndReceycleAction, it seems like it would probably make more sense to simplify this public method to be DeleteEmptyContainingFolders and let each caller handle the first bit of logic separately.

**Comment by tombogle** [comment]
___
*[Glyssen/Project.cs, line 2278 at r1](https://reviewable.io/reviews/sillsdev/glyssen/588#-LxvkZxR47pWMhaoTdns:-LxvkZxR47pWMhaoTdnt:b-sp0k41) ([raw file](https://github.com/sillsdev/glyssen/blob/939d5e623efb59dd2c77dbea9c2f05d6c8f5df16/Glyssen/Project.cs#L2278)):*
> ```Smalltalk
> 							"The font ({0}) used by this project has not been installed on this computer, and {1} could not find the relevant font files. Either they were not copied from the bundle correctly, or they have been moved. You will need to install {0} yourself. After installing the font, you will need to restart {1} to make use of it."),
> 						m_projectMetadata.FontFamily, GlyssenInfo.kProduct));
> 		}
> ```

This implementation should be moved to SIL.Core. To prevent having it be a breaking change, a deprecated pass-through implementation can be kept in SIL.Windows.Forms.

**Comment by AndrewChristensenFCBH** [comment]
> 
> 
> _[Glyssen/Program.cs, line 8 at r1](https://reviewable.io/reviews/sillsdev/glyssen/588#-LxveKpv9ydAR4QWV1rW:-LxveKpv9ydAR4QWV1rX:buonpeb) ([raw file](https://github.com/sillsdev/glyssen/blob/939d5e623efb59dd2c77dbea9c2f05d6c8f5df16/Glyssen/Program.cs#L8)):_
> 
> > ```smalltalk
> > using System.Linq;
> > using System.Windows.Forms;
> > using DesktopAnalytics;
> > ```
> 
> Is this using still needed? Looks like you're now having to make this explicit.

Yes, it is still needed for line 76.  UserInfo and UILanguageCode both need this statement.
UserInfo userInfo = new UserInfo { UILanguageCode = Settings.Default.UserInterfaceLanguage };

**Comment by AndrewChristensenFCBH** [comment]
> 
> 
> _[Glyssen/DataMigrator.cs, line 32 at r1](https://reviewable.io/reviews/sillsdev/glyssen/588#-LxvfOhaD4wDrc3HeDcX:-LxvfOhb9EYxDET9jLlX:b-zgoiz1) ([raw file](https://github.com/sillsdev/glyssen/blob/939d5e623efb59dd2c77dbea9c2f05d6c8f5df16/Glyssen/DataMigrator.cs#L32)):_
> 
> > ```smalltalk
> > 		}
> > 
> > 		private static bool UpgradeToCurrentDataFormatVersion(ApplicationMetadata info, Func<string, string, bool> confirmAndRecycleAction, out string warning)
> > ```
> 
> I see you've added two new parameters here, but other than setting the warning string to null, they don't seem to be used. Did you forget something?

Warning was not needed and I have removed it. confirmAndRecycleAction is needed and is used on line 113.

**Comment by AndrewChristensenFCBH** [comment]
> 
> 
> _[Glyssen/DataMigrator.cs, line 34 at r1](https://reviewable.io/reviews/sillsdev/glyssen/588#-LxvfkVr2hAIaOdQJgQl:-LxvfkVr2hAIaOdQJgQm:b-ge5mj8) ([raw file](https://github.com/sillsdev/glyssen/blob/939d5e623efb59dd2c77dbea9c2f05d6c8f5df16/Glyssen/DataMigrator.cs#L34)):_
> 
> > ```smalltalk
> > 		private static bool UpgradeToCurrentDataFormatVersion(ApplicationMetadata info, Func<string, string, bool> confirmAndRecycleAction, out string warning)
> > 		{
> > 			warning = null;
> > ```
> 
> What is this warning parameter for? It only ever gets set to null.

This isn't needed after all. This has been replaced by a MessageModal (MessageBox) call so it isn't needed after all.  It was used to bubble up the error message.

**Comment by AndrewChristensenFCBH** [comment]
> 
> 
> _[Glyssen/DataMigrator.cs, line 111 at r1](https://reviewable.io/reviews/sillsdev/glyssen/588#-LxvgWg1-xx1AZZGwnOI:-LxvgWg1-xx1AZZGwnOJ:bjycapo) ([raw file](https://github.com/sillsdev/glyssen/blob/939d5e623efb59dd2c77dbea9c2f05d6c8f5df16/Glyssen/DataMigrator.cs#L111)):_
> 
> > ```smalltalk
> > 										// so for this step in the migration process (going from 0 to 1), any project without
> > 										// OriginalReleaseBundlePath set is invalid (possibly from a really early version of Glyssen
> > 										// or some g;itch arising from development activity or external mangling of the file). So
> > ```
> 
> If you make other changes to this file, please fix this typo.

Done.

**Comment by AndrewChristensenFCBH** [comment]
> 
> 
> _[Glyssen/Project.cs, line 1249 at r1](https://reviewable.io/reviews/sillsdev/glyssen/588#-Lxvj5JHDhC-2BxNxtMM:-Lxvj5JI387tz-XoL18W:bi7ex4y) ([raw file](https://github.com/sillsdev/glyssen/blob/939d5e623efb59dd2c77dbea9c2f05d6c8f5df16/Glyssen/Project.cs#L1249)):_
> 
> > ```smalltalk
> > 		}
> > 
> > 		public static void DeleteProjectFolderAndEmptyContainingFolders(string projectFolder, Func<string, string, bool> confirmAndRecycleAction = null)
> > ```
> 
> With only two callers and one of them never passing in a confirmAndReceycleAction, it seems like it would probably make more sense to simplify this public method to be DeleteEmptyContainingFolders and let each caller handle the first bit of logic separately.

Done. Please review this carefully.

**Comment by AndrewChristensenFCBH** [comment]
> 
> 
> _[Glyssen/Project.cs, line 2278 at r1](https://reviewable.io/reviews/sillsdev/glyssen/588#-LxvkZxR47pWMhaoTdns:-LxvkZxR47pWMhaoTdnt:b-sp0k41) ([raw file](https://github.com/sillsdev/glyssen/blob/939d5e623efb59dd2c77dbea9c2f05d6c8f5df16/Glyssen/Project.cs#L2278)):_
> 
> > ```smalltalk
> > 							"The font ({0}) used by this project has not been installed on this computer, and {1} could not find the relevant font files. Either they were not copied from the bundle correctly, or they have been moved. You will need to install {0} yourself. After installing the font, you will need to restart {1} to make use of it."),
> > 						m_projectMetadata.FontFamily, GlyssenInfo.kProduct));
> > 		}
> > ```
> 
> This implementation should be moved to SIL.Core. To prevent having it be a breaking change, a deprecated pass-through implementation can be kept in SIL.Windows.Forms.

I am not sure what you want me to do and not sure I should be the one doing it.

**Comment by tombogle** [comment]
___
*[Glyssen/Project.cs, line 2278 at r1](https://reviewable.io/reviews/sillsdev/glyssen/588#-LxvkZxR47pWMhaoTdns:-LxwFl7w8-zyd7ZRc32S:b8c0ni4) ([raw file](https://github.com/sillsdev/glyssen/blob/939d5e623efb59dd2c77dbea9c2f05d6c8f5df16/Glyssen/Project.cs#L2278)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I'll take a quick look at what this would look like.
</blockquote></details>

I can attempt the change if you want.

**Comment by tombogle** [comment]
___
*[Glyssen/DataMigrator.cs, line 116 at r3](https://reviewable.io/reviews/sillsdev/glyssen/588#-LxwDYJe-fuKTpZE7Ajz:-LxwG8eo2eK7t7ca1fDE:b-y0a4jf) ([raw file](https://github.com/sillsdev/glyssen/blob/3f025e498131257e078a4dfcf88f28052357fad8/Glyssen/DataMigrator.cs#L116)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Bummer. So we still have to have this action passed in since DataMigrator will be moved to GlyssenEngine, too...
Tom, any thoughts on further simplifying?

This can't return here. Rather, it needs to let execution just continue (but not call Project.DeleteEmptyContainingFolders) or call `goto case 2;`
</blockquote></details>

That was the best I could do without any change in behavior. The only additional "simplification" would be to just remove it. It is/was to handle a very unlikely condition that by now is pretty much guaranteed to never occur. It could only happen if someone were to upgrade from a REALLY old version of Glyssen. Even as it is, the user can already choose not to do delete, so we already handle that case. I think I could be talked into just removing the entire positive code block for the if (string.IsNullOrEmpty(origBundlePath)) condition in DataMigrator (keeping a modified version of the comment for posterity's sake).

**Comment by tombogle** [comment]
___
*[Glyssen/Project.cs, line 2278 at r1](https://reviewable.io/reviews/sillsdev/glyssen/588#-LxvkZxR47pWMhaoTdns:-LxwIQ5m1iFjW9o1htBL:bzbg7j0) ([raw file](https://github.com/sillsdev/glyssen/blob/939d5e623efb59dd2c77dbea9c2f05d6c8f5df16/Glyssen/Project.cs#L2278)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

To clarify, I'm voting we don't hold up the PR for this change.
</blockquote></details>

Well, I wondered about that. But if it really isn't supported by .Net Standard, then moving it to GlyssenEngine shouldn't work either. I'm okay with not holding up the refactoring and coming back around to improve this later, but I want to be 100% sure it's really going to work at runtime. We need to be sure this code path is hit and that the returned results are as expected.

**Comment by tombogle** [comment]
___
*[Glyssen/Project.cs, line 1249 at r1](https://reviewable.io/reviews/sillsdev/glyssen/588#-Lxvj5JHDhC-2BxNxtMM:-LxwKMmuCJNXvGX-ewUo:b-8b9lsg) ([raw file](https://github.com/sillsdev/glyssen/blob/939d5e623efb59dd2c77dbea9c2f05d6c8f5df16/Glyssen/Project.cs#L1249)):*
<details><summary><i>Previously, AndrewChristensenFCBH (Andrew Christensen) wrote…</i></summary><blockquote>

Done. Please review this carefully.  
</blockquote></details>

Per the discussion in DataMigrator.cs, the only call to this method will now be in Project, so it can be made private (and be put back to DeleteProjectFolderAndEmptyContainingFolders as it was, minus the confirmAndRecycle code).

**Comment by AndrewChristensenFCBH** [comment]
> 
> 
> > Reviewed 2 of 2 files at r4.
> > _[Reviewable](https://reviewable.io/reviews/sillsdev/glyssen/588)_ status: all files reviewed, 2 unresolved discussions (waiting on @andrew-polk, @AndrewChristensenFCBH, and @tombogle)
> 
> _[Glyssen/Project.cs, line 1249 at r1](https://reviewable.io/reviews/sillsdev/glyssen/588#-Lxvj5JHDhC-2BxNxtMM:-LxwfGKK91XR9vBgX9me:b-4l8blh) ([raw file](https://github.com/sillsdev/glyssen/blob/939d5e623efb59dd2c77dbea9c2f05d6c8f5df16/Glyssen/Project.cs#L1249)):_
> 
> > ```
> > 				if (Directory.Exists(ProjectFolder))
> > 					Directory.Delete(ProjectFolder, true);
> > ```
> 
> Let's move this (from the calling code above) back into the method.

Done.

**Comment by tombogle** [comment]
___
*[Glyssen/Project.cs, line 2278 at r1](https://reviewable.io/reviews/sillsdev/glyssen/588#-LxvkZxR47pWMhaoTdns:-LxwmPpUEVLvO1IXHVVP:b-miyzv8) ([raw file](https://github.com/sillsdev/glyssen/blob/939d5e623efb59dd2c77dbea9c2f05d6c8f5df16/Glyssen/Project.cs#L2278)):*
<details><summary><i>Previously, tombogle (Tom Bogle) wrote…</i></summary><blockquote>

Well, I wondered about that. But if it really isn't supported by .Net Standard, then moving it to GlyssenEngine shouldn't work either. I'm okay with not holding up the refactoring and coming back around to improve this later, but I want to be 100% sure it's really going to work at runtime. We need to be sure this code path is hit and that the returned results are as expected.
</blockquote></details>

I vote for actually adding a TODO comment in the code to help ensure we come back to this.

**Comment by andrew-polk** [comment]
Merged via #589

**Pull request merged**
