### PR TITLE
PTX-22878/PTX-22920: Improved CharacterVerse.txt

### PR DESCRIPTION
**Pull request by tombogle**
The changes in JHN 3 reflect the reality that not all translations consider Jesus to be speaking through the end of the chapter. This change prevents test errors in Paratext arising from an unmet expectation in DBL test data.
The changes to make many normal quotes Implicit and the addition of the Position filed are intended to make it easier for Paratext to know whether a quote was left open or continuers are missing.

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/glyssen/843)

### CODE REVIEW

**Review by jwickberg — COMMENTED** [review]
I browsed the code changes and didn't see anything I thought was wrong, but didn't follow the logic closely since I'm not familiar with the Glyssen code.

I sampled a few spots in the new "CharacterVerse.txt" file and was wondering when "EntireVerse" should be used. It seemed to only occur when there were two verses and the second was implicit. If there are more than two verses - like GEN 12:11-13, verses 12 & 13 are not marked "EntireVerse", though all the text of the verses is part of the quote (at least in the ESV).

I'll leave it to Andrew to do the final approval.

**Comment by tombogle** [comment]
GEN 12:12-13 have a quote type of Implicit which already implies that the quote covers the entire verse. So my little dev tool just skipped any lines marked as implicit and didn't even bother to analyze the text for those verses. But I can see how that makes the control file look a little weird. I guess there is no point in even storing the "EntireVerse" value since it should always correspond to one of the two implicit types.

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 8 of 12 files at r1, 13 of 19 files at r2, 17 of 17 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/glyssen/843)* status: all files reviewed, 2 unresolved discussions (waiting on @tombogle)

___
*[`GlyssenEngine/Quote/QuoteParser.cs` line 250 at r3](https://reviewable.io/reviews/sillsdev/glyssen/843#-NMUGNZC7aEG42GoEbjI:-NMUGNZC7aEG42GoEbjJ:b-an5p2s) ([raw file](https://github.com/sillsdev/glyssen/blob/dd9514fcfaf07aa38f5d24b43b78b7ac8d585659/GlyssenEngine/Quote/QuoteParser.cs#L250)):*
> ```Smalltalk
> 
> 				if (block.IsPredeterminedFirstLevelQuoteStart /* ||
> 				    m_quoteSystem.StylesToTreatImplicitlyAsSpeech.Contains(block.StyleTag)*/)
> ```

Just pointing this out in case this was not intended to be left in this state.
___
*[`GlyssenEngine/Script/BookScript.cs` line 1120 at r3](https://reviewable.io/reviews/sillsdev/glyssen/843#-NMVVnV30CdQbNlWFkvf:-NMVVnV30CdQbNlWFkvg:b-xxn252) ([raw file](https://github.com/sillsdev/glyssen/blob/dd9514fcfaf07aa38f5d24b43b78b7ac8d585659/GlyssenEngine/Script/BookScript.cs#L1120)):*
> ```Smalltalk
> 		}
> 
> 		public QuotePosition GetProposedQuotePosition(int chapter, int verse, string character)
> ```

I'm not following the logic here and therefore not understanding what this is trying to do. A method comment would be helpful.

I take it this is the main thing the plugin will use?
So probably worth a comment about what its general purpose is as a method, but also specifically stating what its purpose in the plugin is?

**Comment by tombogle** [comment]
*[`GlyssenEngine/Quote/QuoteParser.cs` line 250 at r3](https://reviewable.io/reviews/sillsdev/glyssen/843#-NMUGNZC7aEG42GoEbjI:-NMVoAbj9VAQZsS14tB8:b-ffbw54) ([raw file](https://github.com/sillsdev/glyssen/blob/dd9514fcfaf07aa38f5d24b43b78b7ac8d585659/GlyssenEngine/Quote/QuoteParser.cs#L250)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Just pointing this out in case this was not intended to be left in this state.
</blockquote></details>

Thanks. Leaving it that way was unintentional.

**Comment by tombogle** [comment]
*[`GlyssenEngine/Script/BookScript.cs` line 1120 at r3](https://reviewable.io/reviews/sillsdev/glyssen/843#-NMVVnV30CdQbNlWFkvf:-NMVrx1U2BVwjDppV53I:b-xzwrsg) ([raw file](https://github.com/sillsdev/glyssen/blob/dd9514fcfaf07aa38f5d24b43b78b7ac8d585659/GlyssenEngine/Script/BookScript.cs#L1120)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I'm not following the logic here and therefore not understanding what this is trying to do. A method comment would be helpful.

I take it this is the main thing the plugin will use?
So probably worth a comment about what its general purpose is as a method, but also specifically stating what its purpose in the plugin is?
</blockquote></details>

I have renamed it, given it a summary, and added a remarks comment to explain both why it is public and what its intended purpose is. Paratext will not consume GlyssenEngine (nor will any currently planned plugin), just GlyssenCharacters. So while this method is public, I have no expectation that anything outside of the Glyssen solution will ever want to use it.

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/glyssen/843)* status: all files reviewed, 2 unresolved discussions (waiting on @tombogle)

___
*[`CHANGELOG.md` line 33 at r4](https://reviewable.io/reviews/sillsdev/glyssen/843#-NMVzZC8Cbb6K1-4eNbl:-NMVzZC98e6HwooUTtZq:bjb7s80) ([raw file](https://github.com/sillsdev/glyssen/blob/670f508b669b74a97c067fbf5f262efbe8df47f3/CHANGELOG.md#L33)):*
> ```Markdown
> - GlyssenCharacters.QuotePosition enum.
> - Optional Quote Position column to CharacterVerse.txt data
> - GlyssenEngine.Script.BookScript.GetProposedQuotePosition method
> ```

You changed the name to GetQuotePosition
___
*[`GlyssenEngine/Script/BookScript.cs` line 1120 at r3](https://reviewable.io/reviews/sillsdev/glyssen/843#-NMVVnV30CdQbNlWFkvf:-NMW-hOfB3waLzfRZyF-:bbao23k) ([raw file](https://github.com/sillsdev/glyssen/blob/dd9514fcfaf07aa38f5d24b43b78b7ac8d585659/GlyssenEngine/Script/BookScript.cs#L1120)):*
<details><summary><i>Previously, tombogle (Tom Bogle) wrote…</i></summary><blockquote>

I have renamed it, given it a summary, and added a remarks comment to explain both why it is public and what its intended purpose is. Paratext will not consume GlyssenEngine (nor will any currently planned plugin), just GlyssenCharacters. So while this method is public, I have no expectation that anything outside of the Glyssen solution will ever want to use it.  
</blockquote></details>

Great, thanks.
I still can't say that I can easily (or entirely!) follow the logic, but I'm sure it makes sense...
That being said, if you wanted to comment on the logic flow in a couple places, that might help future self. Up to you.

**Review by tombogle — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/Glyssen/843)* status: 26 of 28 files reviewed, 2 unresolved discussions (waiting on @andrew-polk)

___
*[`CHANGELOG.md` line 33 at r4](https://reviewable.io/reviews/sillsdev/Glyssen/843#-NMVzZC8Cbb6K1-4eNbl:-NMW_lLO27xUeqOpfLYA:b-896fix) ([raw file](https://github.com/sillsdev/Glyssen/blob/670f508b669b74a97c067fbf5f262efbe8df47f3/CHANGELOG.md#L33)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

You changed the name to GetQuotePosition
</blockquote></details>

Done.
___
*[`GlyssenEngine/Script/BookScript.cs` line 1120 at r3](https://reviewable.io/reviews/sillsdev/Glyssen/843#-NMVVnV30CdQbNlWFkvf:-NMWautA8vFkZlLhnarF:bw38y2x) ([raw file](https://github.com/sillsdev/Glyssen/blob/dd9514fcfaf07aa38f5d24b43b78b7ac8d585659/GlyssenEngine/Script/BookScript.cs#L1120)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Great, thanks.
I still can't say that I can easily (or entirely!) follow the logic, but I'm sure it makes sense...
That being said, if you wanted to comment on the logic flow in a couple places, that might help future self. Up to you.
</blockquote></details>

Yeah, the implementation ended up being nothing at all like I imagined it would be. I started doing the simplest thing that could possibly work to get a few unit tests to pass, and the next thing I knew it was done. I'm not 100% sure, but I think that if I needed to come back and understand it, and I couldn't figure it out, I'd probably run a couple relevant unit tests to see why/how it worked.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/glyssen/843)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tombogle)

___
*[`GlyssenEngine/Script/BookScript.cs` line 1120 at r3](https://reviewable.io/reviews/sillsdev/glyssen/843#-NMVVnV30CdQbNlWFkvf:-NMZcOe95GFMFbRr2I5x:btojbfd) ([raw file](https://github.com/sillsdev/glyssen/blob/dd9514fcfaf07aa38f5d24b43b78b7ac8d585659/GlyssenEngine/Script/BookScript.cs#L1120)):*
<details><summary><i>Previously, tombogle (Tom Bogle) wrote…</i></summary><blockquote>

Yeah, the implementation ended up being nothing at all like I imagined it would be. I started doing the simplest thing that could possibly work to get a few unit tests to pass, and the next thing I knew it was done. I'm not 100% sure, but I think that if I needed to come back and understand it, and I couldn't figure it out, I'd probably run a couple relevant unit tests to see why/how it worked.
</blockquote></details>

Great!

**Pull request merged**
