### PR TITLE
PG-582: Add "All quotes" filter to Assign Characters dialog

### PR DESCRIPTION
**Pull request by phillip-hopper**
Also localizes the filter list items

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/glyssen/126)

### CODE REVIEW

**Comment by andrew-polk** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[Glyssen/Utilities/L10N.cs, line 11 \[r1\]](https://reviewable.io:443/reviews/sillsdev/glyssen/126#-KEky6_dNouCwi9mZJbK:-KEky6_dNouCwi9mZJbL:-1408673490) ([raw file](https://github.com/sillsdev/glyssen/blob/4daaa8314cec3e4f6d14930a6fec24518b440dde/Glyssen/Utilities/L10N.cs#L11)):*
Should we force component to be a ComboBox? Otherwise, it looks like GetItems would return null and the next line will throw.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/glyssen/126)*

**Comment by phillip-hopper** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[Glyssen/Utilities/L10N.cs, line 11 \[r1\]](https://reviewable.io:443/reviews/sillsdev/glyssen/126#-KEky6_dNouCwi9mZJbK:-KEl3XAMnoUbnnaRWbli:1315783250) ([raw file](https://github.com/sillsdev/glyssen/blob/4daaa8314cec3e4f6d14930a6fec24518b440dde/Glyssen/Utilities/L10N.cs#L11)):*
The controls used for filtering are type `ToolStripComboBox`.  `Component` is the closest relative I found that it has in common with `ComboBox`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/glyssen/126)*

**Comment by andrew-polk** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[Glyssen/Utilities/L10N.cs, line 11 \[r1\]](https://reviewable.io:443/reviews/sillsdev/glyssen/126#-KEky6_dNouCwi9mZJbK:-KEl4C6rOkjkXT2rNAaY:-1500228335) ([raw file](https://github.com/sillsdev/glyssen/blob/4daaa8314cec3e4f6d14930a6fec24518b440dde/Glyssen/Utilities/L10N.cs#L11)):*
Can we put in a check to ensure it is one of those two components, then? Or if we think it might apply to others in the future, can we at least return if GetItems returns null?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/glyssen/126)*

**Comment by andrew-polk** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/glyssen/126#-:-KElDSdP3vFbdk1j2onb:1417088721)*

**Pull request merged**
