### PR TITLE
PG-1412: Added validation for Audio Stock Number

### PR DESCRIPTION
**Pull request by tombogle**
This prevents later using it to create an illegal path.
Also did some code cleanup in ProjectSettingsDlg.

Note: this is a WIP because it's waiting on https://github.com/sillsdev/libpalaso/pull/983 (after which I'll need to bump up to the latest beta version of that libpalaso DLL).

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/glyssen/734)

### CODE REVIEW

**Comment by tombogle** [comment]
___
*[Glyssen/Dialogs/ProjectSettingsDlg.cs, line 482 at r1](https://reviewable.io/reviews/sillsdev/glyssen/734#-MKuUt-6Ep9CKaY23Ci0:-MKuq2VY1tWCP09PMs6s:b-784oo3) ([raw file](https://github.com/sillsdev/glyssen/blob/3c6c57c6d85ef0272a412c125b7fa21438b1f491/Glyssen/Dialogs/ProjectSettingsDlg.cs#L482)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Just know that this could make future evaluation of your data confusing. There will be two columns with some rows populating one and some another.
</blockquote></details>

Yeah, I thought about that, but this is a pretty rare event and I don't usually spend much time looking at Analytics anyway. I decided that making it right was better.

**Comment by tombogle** [comment]
___
*[Glyssen/Dialogs/ProjectSettingsDlg.cs, line 809 at r1](https://reviewable.io/reviews/sillsdev/glyssen/734#-MKuWSOQ2r6X9y8EFjAe:-MKuqMtl7tZGHcNdl23g:bwz2kwq) ([raw file](https://github.com/sillsdev/glyssen/blob/3c6c57c6d85ef0272a412c125b7fa21438b1f491/Glyssen/Dialogs/ProjectSettingsDlg.cs#L809)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I must be missing something, but this appears to be putting the value in the error message instead of the label.
</blockquote></details>

The errorMsg has the {0} in it. The Regex.Replace strips any leading/trailing punctuation, numbers, symbols, etc. off the label "Audio Stock Number:" (this is to get rid of the trialing colon). it might have been clearer to just use String.Replace(":", "") but I was trying to anticipate possible localizations that might use something other than a colon.

**Review by andrew-polk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/glyssen/734)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[Glyssen/Dialogs/ProjectSettingsDlg.cs, line 809 at r1](https://reviewable.io/reviews/sillsdev/glyssen/734#-MKuWSOQ2r6X9y8EFjAe:-MKv12oUAcpDXgQRUge2:bz2ye8n) ([raw file](https://github.com/sillsdev/glyssen/blob/3c6c57c6d85ef0272a412c125b7fa21438b1f491/Glyssen/Dialogs/ProjectSettingsDlg.cs#L809)):*
<details><summary><i>Previously, tombogle (Tom Bogle) wrote…</i></summary><blockquote>

The errorMsg has the {0} in it. The Regex.Replace strips any leading/trailing punctuation, numbers, symbols, etc. off the label "Audio Stock Number:" (this is to get rid of the trialing colon). it might have been clearer to just use String.Replace(":", "") but I was trying to anticipate possible localizations that might use something other than a colon.
</blockquote></details>

Sorry; I had figured this out and forgot to delete the comment.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 28 of 28 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/glyssen/734)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
