### PR TITLE
PG-1434 [WIP]: In UsxParser, prevent non-scripture blocks at end of book

### PR DESCRIPTION
**Pull request by tombogle**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/glyssen/769)

### CODE REVIEW

**Review by andrew-polk — COMMENTED** [review]
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/glyssen/769)* status: all files reviewed, 2 unresolved discussions (waiting on @tombogle)

___
*[GlyssenEngine/UsxParser.cs, line 289 at r1](https://reviewable.io/reviews/sillsdev/glyssen/769#-MTvJS-1BZn0BGq39fHt:-MTvJS-1BZn0BGq39fHu:bc012yz) ([raw file](https://github.com/sillsdev/glyssen/blob/414ad06a130a4d823717b5a043206fd3884ae16c/GlyssenEngine/UsxParser.cs#L289)):*
> ```Smalltalk
> 				blocks.RemoveAt(blocks.Count - 1);
> 				lastBlock = blocks.LastOrDefault();
> 			}
> ```

Won't this leave chapter 0 information as the only thing in the book? Is that what we want?
___
*[GlyssenEngineTests/UsxParserTests.cs, line 110 at r1](https://reviewable.io/reviews/sillsdev/glyssen/769#-MTvK0h65ug9NFpO_QEj:-MTvK0h65ug9NFpO_QEk:b-e6q9qi) ([raw file](https://github.com/sillsdev/glyssen/blob/414ad06a130a4d823717b5a043206fd3884ae16c/GlyssenEngineTests/UsxParserTests.cs#L110)):*
> ```
> Parse_NoScriptureTextFollowingFinalChapter_FinalChapterOmitted
> ```
I think this would be clearer as `Parse_NoScriptureTextFollowingFinalChapterMarker_FinalChapterOmitted`

**Comment by tombogle** [comment]
___
*[GlyssenEngine/UsxParser.cs, line 289 at r1](https://reviewable.io/reviews/sillsdev/glyssen/769#-MTvJS-1BZn0BGq39fHt:-MU8wptM9PfOr8emqyno:b-5ry1ig) ([raw file](https://github.com/sillsdev/glyssen/blob/414ad06a130a4d823717b5a043206fd3884ae16c/GlyssenEngine/UsxParser.cs#L289)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Won't this leave chapter 0 information as the only thing in the book? Is that what we want?
</blockquote></details>

This is a WIP. We definitely do not want chapter 0 as the last thing, nor a trailing section head.

**Comment by tombogle** [comment]
___
*[GlyssenEngineTests/UsxParserTests.cs, line 110 at r1](https://reviewable.io/reviews/sillsdev/glyssen/769#-MTvK0h65ug9NFpO_QEj:-MU8zHziC1f1e_10CnPU:b-896fix) ([raw file](https://github.com/sillsdev/glyssen/blob/414ad06a130a4d823717b5a043206fd3884ae16c/GlyssenEngineTests/UsxParserTests.cs#L110)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> Parse_NoScriptureTextFollowingFinalChapter_FinalChapterOmitted
> ```
I think this would be clearer as `Parse_NoScriptureTextFollowingFinalChapterMarker_FinalChapterOmitted`
</blockquote></details>

Done.

**Review by andrew-polk — COMMENTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/glyssen/769)* status: all files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

**Comment by tombogle** [comment]
___
*[GlyssenEngine/UsxParser.cs, line 289 at r1](https://reviewable.io/reviews/sillsdev/glyssen/769#-MTvJS-1BZn0BGq39fHt:-MU8zqb649KbPLicIEwz:b-spddal) ([raw file](https://github.com/sillsdev/glyssen/blob/414ad06a130a4d823717b5a043206fd3884ae16c/GlyssenEngine/UsxParser.cs#L289)):*
<details><summary><i>Previously, tombogle (Tom Bogle) wrote…</i></summary><blockquote>

This is a WIP. We definitely do not want chapter 0 as the last thing, nor a trailing section head.
</blockquote></details>

Just thought about this a little more. I'm not 100% sure, but I think this would make it possible to have a book consisting entirely of intro material (chapter 0). I'll probably need to test this, but I don't think it will cause any problems.

**Comment by tombogle** [comment]
___
*[GlyssenEngine/UsxParser.cs, line 289 at r1](https://reviewable.io/reviews/sillsdev/glyssen/769#-MTvJS-1BZn0BGq39fHt:-MUPDY4s1hQhGxjaGVBN:b-womdn8) ([raw file](https://github.com/sillsdev/glyssen/blob/414ad06a130a4d823717b5a043206fd3884ae16c/GlyssenEngine/UsxParser.cs#L289)):*
<details><summary><i>Previously, tombogle (Tom Bogle) wrote…</i></summary><blockquote>

Just thought about this a little more. I'm not 100% sure, but I think this would make it possible to have a book consisting entirely of intro material (chapter 0). I'll probably need to test this, but I don't think it will cause any problems.
</blockquote></details>

I checked. It's a little weird because you can't actually navigate to the book in ISP (because it has no Scripture blocks and we don't have an "All Blocks" filter), but it does work fine and comes out in the export as expected. So although it's unlikely and unusual, I don't think there's any reason to prevent it.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/glyssen/769)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
