### PR TITLE
PTX-23266: Added a few more rare/potential quote instances to control files

### PR DESCRIPTION
**Pull request by tombogle**
Upgraded dependencies

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/Glyssen/849)

### CODE REVIEW

**Review by tombogle — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/Glyssen/849)* status: 25 of 27 files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[`GlyssenCharacters/Resources/CharacterVerse.txt` line 17328 at r1](https://reviewable.io/reviews/sillsdev/Glyssen/849#-NPdIqarBVedwSG71dPt:-NPr8m907ain9KeNYVs4:b-896fix) ([raw file](https://github.com/sillsdev/Glyssen/blob/89f55f390087267f9f9c3f74f14fe4eec49daaf6/GlyssenCharacters/Resources/CharacterVerse.txt#L17328)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Does the version number need to bump?
Otherwise, LGTM
</blockquote></details>

Done.

**Review by andrew-polk — COMMENTED** [review]
> Reviewed 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/Glyssen/849)* status: 26 of 27 files reviewed, 1 unresolved discussion (waiting on @tombogle)

___
*[`GlyssenCharacters/Resources/CharacterVerse.txt` line 20448 at r2](https://reviewable.io/reviews/sillsdev/Glyssen/849#-NPrVzpT7MrHYotW_UT6:-NPrVzpT7MrHYotW_UT7:b3yc2g4) ([raw file](https://github.com/sillsdev/Glyssen/blob/5be0904f1022aa988ccf0cd46d21bbf6b65c886a/GlyssenCharacters/Resources/CharacterVerse.txt#L20448)):*
> ```help
> GAL	1	23	narrator-GAL			Quotation			Unspecified
> GAL	1	23	report concerning Paul			Quotation	narrator-GAL		Unspecified
> # The word "pillars" might have scare quotes. Some looser translatios may have the implied
> ```

typo
Feel free to merge before or after correcting.



_Code quote:_
```help
translatios
```

**Review by andrew-polk — APPROVED** [review]
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/Glyssen/849)* status: all files reviewed, 1 unresolved discussion (waiting on @tombogle)

**Review by andrew-polk — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/Glyssen/849)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tombogle)

**Pull request merged**
