### PR TITLE
PG-1494/PG-1495: Do not allow an interruption ID to be assigned to a block

### PR DESCRIPTION
**Pull request by tombogle**
Also, prevent the user from assigning or adding any ID that would be considered extra-biblical.

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/Glyssen/854)

### CODE REVIEW

**Review by tombogle — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/Glyssen/854)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[`GlyssenCharacters/CharacterVerseData.cs` line 130 at r1](https://reviewable.io/reviews/sillsdev/Glyssen/854#-NUwh8g2ASiDdSvephWC:-NUxCakr99Ia_XNN_ZSI:b-896fix) ([raw file](https://github.com/sillsdev/Glyssen/blob/354ad7b4228674ccce64cc05123db71ce5715d05/GlyssenCharacters/CharacterVerseData.cs#L130)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Probably worth a comment explaining the length thing here, too.
Or, probably better yet, maybe extract `IsInterruptionCharacter` for use here and in migration code.
</blockquote></details>

Done.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/Glyssen/854)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tombogle)

___
*[`GlyssenCharacters/CharacterVerseData.cs` line 130 at r1](https://reviewable.io/reviews/sillsdev/Glyssen/854#-NUwh8g2ASiDdSvephWC:-NUxEjah5UGo5ofs2SA2:b3hy613) ([raw file](https://github.com/sillsdev/Glyssen/blob/354ad7b4228674ccce64cc05123db71ce5715d05/GlyssenCharacters/CharacterVerseData.cs#L130)):*
<details><summary><i>Previously, tombogle (Tom Bogle) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Feel free to merge if you aren't going to extract the method.
Though the new comment has a typo -- "as a the" -- (duplicated in both places).

**Comment by tombogle** [comment]
*[`GlyssenCharacters/CharacterVerseData.cs` line 130 at r1](https://reviewable.io/reviews/sillsdev/Glyssen/854#-NUwh8g2ASiDdSvephWC:-NV0DUxh4ReVx8Md62hR:b-gomiqb) ([raw file](https://github.com/sillsdev/Glyssen/blob/354ad7b4228674ccce64cc05123db71ce5715d05/GlyssenCharacters/CharacterVerseData.cs#L130)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Feel free to merge if you aren't going to extract the method.
Though the new comment has a typo -- "as a the" -- (duplicated in both places).
</blockquote></details>

Oops. Totally missed that suggestion.

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/Glyssen/854)* status: all files reviewed, 2 unresolved discussions (waiting on @tombogle)

___
*[`CHANGELOG.md` line 22 at r3](https://reviewable.io/reviews/sillsdev/Glyssen/854#-NV0N_Oi6h7vP9tKS5tr:-NV0N_Oi6h7vP9tKS5ts:b-lcmpsz) ([raw file](https://github.com/sillsdev/Glyssen/blob/a21c99f4f1c8374cb9831523e841f61dc9b2aae0/CHANGELOG.md#L22)):*
> ```Markdown
> 
> ### Changed
> - In CharacterVerseData (and in its concrete implementations with overrides: ControlCharacterVerseData and CombinedCharacterVerseData), GetUniqueCharacterDeliveryAliasInfo and GetUniqueCharacterDeliveryInfo fixed so that they always excludes interruptions (since they are intended only for use in compiling a list of characters for user assignment).
> ```

excludes => exclude
___
*[`GlyssenCharacters/CharacterVerseData.cs` line 130 at r1](https://reviewable.io/reviews/sillsdev/Glyssen/854#-NUwh8g2ASiDdSvephWC:-NV0OynC8hT-w81Wy3dg:bnsd72i) ([raw file](https://github.com/sillsdev/Glyssen/blob/354ad7b4228674ccce64cc05123db71ce5715d05/GlyssenCharacters/CharacterVerseData.cs#L130)):*
<details><summary><i>Previously, tombogle (Tom Bogle) wrote…</i></summary><blockquote>

Oops. Totally missed that suggestion.
</blockquote></details>

Still have the comment typos.
___
*[`GlyssenCharactersTests/CharacterVerseDataTests.cs` line 74 at r3](https://reviewable.io/reviews/sillsdev/Glyssen/854#-NV0O_93BNmATDK71ih9:-NV0O_93BNmATDK71ihA:b-gea8r8) ([raw file](https://github.com/sillsdev/Glyssen/blob/a21c99f4f1c8374cb9831523e841f61dc9b2aae0/GlyssenCharactersTests/CharacterVerseDataTests.cs#L74)):*
> ```Smalltalk
> 		[TestCase("interruption-JHN")]
> 		[TestCase("interruption-FRG")]
> 		public void IsInterruption_Interruption_ReturnsFalse(string characterId)
> ```

ReturnsTrue

**Review by tombogle — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/Glyssen/854)* status: 7 of 10 files reviewed, 2 unresolved discussions (waiting on @andrew-polk and @tombogle)

___
*[`CHANGELOG.md` line 22 at r3](https://reviewable.io/reviews/sillsdev/Glyssen/854#-NV0N_Oi6h7vP9tKS5tr:-NV1NKP97dvEmqdiLJ1N:b-896fix) ([raw file](https://github.com/sillsdev/Glyssen/blob/a21c99f4f1c8374cb9831523e841f61dc9b2aae0/CHANGELOG.md#L22)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

excludes => exclude
</blockquote></details>

Done.

**Review by tombogle — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/Glyssen/854)* status: 7 of 10 files reviewed, 2 unresolved discussions (waiting on @andrew-polk)

___
*[`GlyssenCharactersTests/CharacterVerseDataTests.cs` line 74 at r3](https://reviewable.io/reviews/sillsdev/Glyssen/854#-NV0O_93BNmATDK71ih9:-NV1OLlZ2tiMrAnAHFK1:b-896fix) ([raw file](https://github.com/sillsdev/Glyssen/blob/a21c99f4f1c8374cb9831523e841f61dc9b2aae0/GlyssenCharactersTests/CharacterVerseDataTests.cs#L74)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

ReturnsTrue
</blockquote></details>

Done.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/Glyssen/854)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tombogle)

**Pull request merged**
