### PR TITLE
PG-585: Allow user to assign characters in splitting dialog

### PR DESCRIPTION
**Pull request by phillip-hopper**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/glyssen/191)

### CODE REVIEW

**Comment by andrew-polk** [comment]
Reviewed 15 of 15 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[Glyssen/Dialogs/SplitBlockDlg.cs, line 41 \[r1\]](https://reviewable.io:443/reviews/sillsdev/glyssen/191#-KJL_NWPHXFA_8xgBuaK:-KJL_NWPHXFA_8xgBuaL:1711132313) ([raw file](https://github.com/sillsdev/glyssen/blob/8d7097dffbbcba4e0df9d911d4dc38b6fbdfc7fc/Glyssen/Dialogs/SplitBlockDlg.cs#L41)):*
> ```Smalltalk
> 			if (viewModel != null)
> 			{
> 				m_characters = viewModel.GetCharactersForCurrentReference();
> ```

Somehow, this doesn't seem to be working correctly for me when I run it. I get narrator and scripture every time.

---

*[Glyssen/Dialogs/SplitBlockDlg.cs, line 286 \[r1\]](https://reviewable.io:443/reviews/sillsdev/glyssen/191#-KJLZLIhXKgZlYPOGBkR:-KJLZLIhXKgZlYPOGBkS:499877674) ([raw file](https://github.com/sillsdev/glyssen/blob/8d7097dffbbcba4e0df9d911d4dc38b6fbdfc7fc/Glyssen/Dialogs/SplitBlockDlg.cs#L286)):*
> ```Smalltalk
> 		{
> 			//// if we are looking for the end, do it now
> 			//if (selectLastIndex)
> ```

Did you mean to leave in this commented code for future reference?

---

*[Glyssen/Dialogs/SplitBlockDlg.cs, line 356 \[r1\]](https://reviewable.io:443/reviews/sillsdev/glyssen/191#-KJLYREN3gI4qlH-98N7:-KJLYREN3gI4qlH-98N8:499877674) ([raw file](https://github.com/sillsdev/glyssen/blob/8d7097dffbbcba4e0df9d911d4dc38b6fbdfc7fc/Glyssen/Dialogs/SplitBlockDlg.cs#L356)):*
> ```Smalltalk
> 		}
> 
> 		//private bool DetermineSplitLocationAtStartOfVerse(GeckoDivElement blockElement, string verseElementInnerHtml)
> ```

Did you mean to leave in this commented code for future reference?

---

*[GlyssenTests/BlockTests.cs, line 169 \[r1\]](https://reviewable.io:443/reviews/sillsdev/glyssen/191#-KJLdoyeRCxDeE_LPhgv:-KJLdoyeRCxDeE_LPhgw:481090842) ([raw file](https://github.com/sillsdev/glyssen/blob/8d7097dffbbcba4e0df9d911d4dc38b6fbdfc7fc/GlyssenTests/BlockTests.cs#L169)):*
> ```Smalltalk
> 			var actual = block.GetTextAsHtml(true, false);
> 
> 			Assert.IsTrue(actual.Contains(expected), string.Format("The output string did not contain: {0}", expected));
> ```

Does this need to be contains now that GetTextAsHtml and GetSplitTextAsHtml are two different methods? Same question applies to tests below.

---

*[GlyssenTests/BlockTests.cs, line 211 \[r1\]](https://reviewable.io:443/reviews/sillsdev/glyssen/191#-KJLeIlTQK7PiwRp1J14:-KJLeIlTQK7PiwRp1J15:1755185050) ([raw file](https://github.com/sillsdev/glyssen/blob/8d7097dffbbcba4e0df9d911d4dc38b6fbdfc7fc/GlyssenTests/BlockTests.cs#L211)):*
> ```Smalltalk
> 
> 		[Test]
> 		public void GetTextAsHtml_OffsetTooHigh_ThrowsArgumentOutOfRangeException()
> ```

Name of test should be GetSplitText... Same comment applies to tests below.

---

*[GlyssenTests/BlockTests.cs, line 234 \[r1\]](https://reviewable.io:443/reviews/sillsdev/glyssen/191#-KJLeUTBHfnAuptP82IZ:-KJLeUTBHfnAuptP82I_:1665691225) ([raw file](https://github.com/sillsdev/glyssen/blob/8d7097dffbbcba4e0df9d911d4dc38b6fbdfc7fc/GlyssenTests/BlockTests.cs#L234)):*
> ```Smalltalk
> 			Assert.IsTrue(actual.Contains(expected), string.Format("The output string did not contain: {0}", expected));
> 
> 			//var outputHtml = block.GetTextAsHtml(true, false, new[] {new BlockSplitData(0, block, "4", 5)});
> ```

Did you mean to leave in the commented code for future reference?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/glyssen/191)*

**Comment by phillip-hopper** [comment]
Review status: 11 of 15 files reviewed at latest revision, 6 unresolved discussions.

---

*[Glyssen/Dialogs/SplitBlockDlg.cs, line 41 \[r1\]](https://reviewable.io:443/reviews/sillsdev/glyssen/191#-KJL_NWPHXFA_8xgBuaK:-KJfNZXvKo3vC3ooNPTP:-499146009) ([raw file](https://github.com/sillsdev/glyssen/blob/8d7097dffbbcba4e0df9d911d4dc38b6fbdfc7fc/Glyssen/Dialogs/SplitBlockDlg.cs#L41)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary>
> Somehow, this doesn't seem to be working correctly for me when I run it. I get narrator and scripture every time.
</details>
Done.

---

*[Glyssen/Dialogs/SplitBlockDlg.cs, line 286 \[r1\]](https://reviewable.io:443/reviews/sillsdev/glyssen/191#-KJLZLIhXKgZlYPOGBkR:-KJf3vScb7yjqm4ISmvB:-499146009) ([raw file](https://github.com/sillsdev/glyssen/blob/8d7097dffbbcba4e0df9d911d4dc38b6fbdfc7fc/Glyssen/Dialogs/SplitBlockDlg.cs#L286)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary>
> Did you mean to leave in this commented code for future reference?
</details>
Done.

---

*[Glyssen/Dialogs/SplitBlockDlg.cs, line 356 \[r1\]](https://reviewable.io:443/reviews/sillsdev/glyssen/191#-KJLYREN3gI4qlH-98N7:-KJf41W6dz6PECaxr9hv:-499146009) ([raw file](https://github.com/sillsdev/glyssen/blob/8d7097dffbbcba4e0df9d911d4dc38b6fbdfc7fc/Glyssen/Dialogs/SplitBlockDlg.cs#L356)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary>
> Did you mean to leave in this commented code for future reference?
</details>
Done.

---

*[GlyssenTests/BlockTests.cs, line 169 \[r1\]](https://reviewable.io:443/reviews/sillsdev/glyssen/191#-KJLdoyeRCxDeE_LPhgv:-KJf63JxEVqebwQ2diuu:-499146009) ([raw file](https://github.com/sillsdev/glyssen/blob/8d7097dffbbcba4e0df9d911d4dc38b6fbdfc7fc/GlyssenTests/BlockTests.cs#L169)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary>
> Does this need to be contains now that GetTextAsHtml and GetSplitTextAsHtml are two different methods? Same question applies to tests below.
</details>
Done.

---

*[GlyssenTests/BlockTests.cs, line 211 \[r1\]](https://reviewable.io:443/reviews/sillsdev/glyssen/191#-KJLeIlTQK7PiwRp1J14:-KJf6_OotiyAoIQ8YmA2:-499146009) ([raw file](https://github.com/sillsdev/glyssen/blob/8d7097dffbbcba4e0df9d911d4dc38b6fbdfc7fc/GlyssenTests/BlockTests.cs#L211)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary>
> Name of test should be GetSplitText... Same comment applies to tests below.
</details>
Done.

---

*[GlyssenTests/BlockTests.cs, line 234 \[r1\]](https://reviewable.io:443/reviews/sillsdev/glyssen/191#-KJLeUTBHfnAuptP82IZ:-KJf6gerpl2ZLOAPFEpI:-499146009) ([raw file](https://github.com/sillsdev/glyssen/blob/8d7097dffbbcba4e0df9d911d4dc38b6fbdfc7fc/GlyssenTests/BlockTests.cs#L234)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary>
> Did you mean to leave in the commented code for future reference?
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/glyssen/191)*

**Comment by andrew-polk** [comment]
:lgtm:

<details><summary><i>Previously, phillip-hopper (Phil Hopper) wrote…</i></summary>
> #### PG\-585: Allow user to assign characters in splitting dialog
</details>


---

Reviewed 1 of 1 files at r2, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/glyssen/191#-:-KK8v3Af6_PfT9iR5CPi:1417088721)*

**Comment by andrew-polk** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/glyssen/191)*

**Pull request merged**
