### PR TITLE
Add new dialog for exporting to HearThis

### PR DESCRIPTION
**Pull request by andrew-polk**
---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/glyssen/393)

### CODE REVIEW

**Comment by JohnThomson** [comment]
Review status: 0 of 7 files reviewed at latest revision, 9 unresolved discussions.

---

*[Glyssen/ScriptExporter.cs, line 13 at r1](https://reviewable.io:443/reviews/sillsdev/glyssen/393#-Kow_B-TDWpiqTQkmsuk:-Kow_B-TDWpiqTQkmsul:b-74n39r) ([raw file](https://github.com/sillsdev/glyssen/blob/0c93581e5a98664688f3189700c5b57de0c9d49b/Glyssen/ScriptExporter.cs#L13)):*
> ```Smalltalk
> 	public static class ScriptExporter
> 	{
> 		public static void MakeGlyssenScriptFile(Project project, IEnumerable<List<object>> data, string outputPath)
> ```

Why can't we declare a meaningful type for the data objects? I think I would be tempted to make an object with the block properties and let another class be responsible for how to create these based on knowing which column each occupies in the output of some other process. (Up to you...I won't insist.)
Could also benefit from a name which indicates that each item corresponds to a block.

---

*[Glyssen/ScriptExporter.cs, line 22 at r1](https://reviewable.io:443/reviews/sillsdev/glyssen/393#-KowfrOEroQALR1rYZvU:-KowfrOEroQALR1rYZvV:b-78w57h) ([raw file](https://github.com/sillsdev/glyssen/blob/0c93581e5a98664688f3189700c5b57de0c9d49b/Glyssen/ScriptExporter.cs#L22)):*
> ```Smalltalk
> 			int chapter = 0;
> 			List<ScriptBlock> blocks = new List<ScriptBlock>();
> 			foreach (var row in data)
> ```

Again the name could indicate that each row is a block.

---

*[Glyssen/ScriptExporter.cs, line 30 at r1](https://reviewable.io:443/reviews/sillsdev/glyssen/393#-Kow_xWusfPfggFxCpOc:-Kow_xWusfPfggFxCpOd:b4n2inr) ([raw file](https://github.com/sillsdev/glyssen/blob/0c93581e5a98664688f3189700c5b57de0c9d49b/Glyssen/ScriptExporter.cs#L30)):*
> ```Smalltalk
> 				if (blockChapterNumber != chapter)
> 				{
> 					chapters.Add(new ScriptChapter {Id = chapter, Blocks = blocks});
> ```

Will this make a spurious chapter 0 with no blocks if the first row is chapter 1?

---

*[Glyssen/ScriptExporter.cs, line 35 at r1](https://reviewable.io:443/reviews/sillsdev/glyssen/393#-KowaOVIV3SvGx2JyYzb:-KowaOVIV3SvGx2JyYzc:bcp5ktx) ([raw file](https://github.com/sillsdev/glyssen/blob/0c93581e5a98664688f3189700c5b57de0c9d49b/Glyssen/ScriptExporter.cs#L35)):*
> ```Smalltalk
> 					chapter = blockChapterNumber;
> 				}
> 				if (bookCode != null && blockBookCode != bookCode)
> ```

Is there any way we could get a changed bookCode without seeing a change of chapter number? If Hebrews has no introduction it seems to me we will create Philemon with no chapters and Hebrews with chapter 1 starting with Philemon's blocks, since the previous end-of-chapter code is not triggered by the move from Philemon 1 to Hebrews 1.

---

*[Glyssen/ScriptExporter.cs, line 68 at r1](https://reviewable.io:443/reviews/sillsdev/glyssen/393#-Kowc2SzpeXLVSiTK86V:-Kowc2SzpeXLVSiTK86W:b-60tgrq) ([raw file](https://github.com/sillsdev/glyssen/blob/0c93581e5a98664688f3189700c5b57de0c9d49b/Glyssen/ScriptExporter.cs#L68)):*
> ```Smalltalk
> 							null,
> 						Tag = (string) row[ProjectExporter.GetColumnIndex(ExportColumn.ParaTag, project)],
> 						VernacularText = new TextWithLanguage { Text = vernacularText},
> ```

Should have language code?

---

*[Glyssen/ScriptExporter.cs, line 72 at r1](https://reviewable.io:443/reviews/sillsdev/glyssen/393#-KowcDSd_-VdgO5QHZgF:-KowcDSd_-VdgO5QHZgG:bvu5apq) ([raw file](https://github.com/sillsdev/glyssen/blob/0c93581e5a98664688f3189700c5b57de0c9d49b/Glyssen/ScriptExporter.cs#L72)):*
> ```Smalltalk
> 					};
> 					var actor = (string) row[ProjectExporter.GetColumnIndex(ExportColumn.Actor, project)];
> 					gsBlock.Actor = !string.IsNullOrEmpty(actor) ? actor : "unassigned";
> ```

Maybe reverse so you don't need NOT operator?

---

*[Glyssen/ScriptExporter.cs, line 73 at r1](https://reviewable.io:443/reviews/sillsdev/glyssen/393#-KowcRDc091rrvlq5IGb:-KowcRDc091rrvlq5IGc:b8e2r6j) ([raw file](https://github.com/sillsdev/glyssen/blob/0c93581e5a98664688f3189700c5b57de0c9d49b/Glyssen/ScriptExporter.cs#L73)):*
> ```Smalltalk
> 					var actor = (string) row[ProjectExporter.GetColumnIndex(ExportColumn.Actor, project)];
> 					gsBlock.Actor = !string.IsNullOrEmpty(actor) ? actor : "unassigned";
> 					Debug.Assert(gsBlock.Actor != "unassigned");
> ```

Is this really a program error? Not assigning blocks feels like a user error that should be reported in production. (But maybe that happens elsewhere?)

---

*[Glyssen/Dialogs/ExportToRecordingToolDlg.cs, line 20 at r1](https://reviewable.io:443/reviews/sillsdev/glyssen/393#-KowdLwybE_4mpsDz5dN:-KowdLwybE_4mpsDz5dO:b-9bcno3) ([raw file](https://github.com/sillsdev/glyssen/blob/0c93581e5a98664688f3189700c5b57de0c9d49b/Glyssen/Dialogs/ExportToRecordingToolDlg.cs#L20)):*
> ```Smalltalk
> 
> 			HandleStringsLocalized();
> 			LocalizeItemDlg.StringsLocalized += HandleStringsLocalized;
> ```

Not sure what this does; looks like adding an event handler, but HandleStringsLocalized isn't a normal one of those. But if storing the function here may cause it to be called more than once (without updating m_lblDescription etc.), note that calling it a second time will fail, since the {0} in m_lblDescription.Text etc. will be wiped out by the first call.

---

*[Glyssen/Dialogs/ViewScriptDlg.cs, line 99 at r1](https://reviewable.io:443/reviews/sillsdev/glyssen/393#-KoweOIURjJXYzIRpqlF:-KoweOIURjJXYzIRpqlG:boql782) ([raw file](https://github.com/sillsdev/glyssen/blob/0c93581e5a98664688f3189700c5b57de0c9d49b/Glyssen/Dialogs/ViewScriptDlg.cs#L99)):*
> ```Smalltalk
> 		private void m_exportToHearThisToolStripMenuItem_Click(object sender, EventArgs e)
> 		{
> 			m_viewModel.TextOnly = true;
> ```

I have no idea why this is necessary, so a comment might be appropriate...also a 'try/finally'?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/glyssen/393)*

**Comment by JohnThomson** [comment]
Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/glyssen/393)*

**Comment by andrew-polk** [comment]
Review status: 2 of 11 files reviewed at latest revision, 9 unresolved discussions.

---

*[Glyssen/ScriptExporter.cs, line 13 at r1](https://reviewable.io:443/reviews/sillsdev/glyssen/393#-Kow_B-TDWpiqTQkmsuk:-KoxCV2uLS9pCLdFUggT:b-xs4dhe) ([raw file](https://github.com/sillsdev/glyssen/blob/0c93581e5a98664688f3189700c5b57de0c9d49b/Glyssen/ScriptExporter.cs#L13)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Why can't we declare a meaningful type for the data objects? I think I would be tempted to make an object with the block properties and let another class be responsible for how to create these based on knowing which column each occupies in the output of some other process. (Up to you...I won't insist.)
Could also benefit from a name which indicates that each item corresponds to a block.
</blockquote></details>

Yes, I started to do that and push it all the way up. It became way too much for this change. I do have some work in progress in that direction I was hoping to do afterward, but, of course, I will never be able to prioritize it...
I suppose I could make use of the object here for now, and then it could be integrated in more piecemeal... I'll look into that. Thanks.

---

*[Glyssen/ScriptExporter.cs, line 22 at r1](https://reviewable.io:443/reviews/sillsdev/glyssen/393#-KowfrOEroQALR1rYZvU:-KoxF0f-bNsDxW9Q1CZN:b-896fix) ([raw file](https://github.com/sillsdev/glyssen/blob/0c93581e5a98664688f3189700c5b57de0c9d49b/Glyssen/ScriptExporter.cs#L22)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Again the name could indicate that each row is a block.
</blockquote></details>

Done.

---

*[Glyssen/ScriptExporter.cs, line 30 at r1](https://reviewable.io:443/reviews/sillsdev/glyssen/393#-Kow_xWusfPfggFxCpOc:-KpHCwNSWyFzS8s99gif:brd9ac5) ([raw file](https://github.com/sillsdev/glyssen/blob/0c93581e5a98664688f3189700c5b57de0c9d49b/Glyssen/ScriptExporter.cs#L30)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Will this make a spurious chapter 0 with no blocks if the first row is chapter 1?
</blockquote></details>

Yes, fixed. Thanks.

---

*[Glyssen/ScriptExporter.cs, line 35 at r1](https://reviewable.io:443/reviews/sillsdev/glyssen/393#-KowaOVIV3SvGx2JyYzb:-KpKgftuFftka4SlbVwS:brd9ac5) ([raw file](https://github.com/sillsdev/glyssen/blob/0c93581e5a98664688f3189700c5b57de0c9d49b/Glyssen/ScriptExporter.cs#L35)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Is there any way we could get a changed bookCode without seeing a change of chapter number? If Hebrews has no introduction it seems to me we will create Philemon with no chapters and Hebrews with chapter 1 starting with Philemon's blocks, since the previous end-of-chapter code is not triggered by the move from Philemon 1 to Hebrews 1.
</blockquote></details>

Yes, fixed. Thanks.

---

*[Glyssen/ScriptExporter.cs, line 68 at r1](https://reviewable.io:443/reviews/sillsdev/glyssen/393#-Kowc2SzpeXLVSiTK86V:-KpGlN31xy1Y_XJ11sat:bkmzyu1) ([raw file](https://github.com/sillsdev/glyssen/blob/0c93581e5a98664688f3189700c5b57de0c9d49b/Glyssen/ScriptExporter.cs#L68)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Should have language code?
</blockquote></details>

I'm going to modify the &lt;script&gt; element to have the vernacular language code. This cascades down to elements beneath unless they have a language set.

---

*[Glyssen/ScriptExporter.cs, line 72 at r1](https://reviewable.io:443/reviews/sillsdev/glyssen/393#-KowcDSd_-VdgO5QHZgF:-KoxF-ak6aouY0jfuEr7:b-896fix) ([raw file](https://github.com/sillsdev/glyssen/blob/0c93581e5a98664688f3189700c5b57de0c9d49b/Glyssen/ScriptExporter.cs#L72)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Maybe reverse so you don't need NOT operator?
</blockquote></details>

Done.

---

*[Glyssen/ScriptExporter.cs, line 73 at r1](https://reviewable.io:443/reviews/sillsdev/glyssen/393#-KowcRDc091rrvlq5IGb:-KpGmuBXu6T1ET8ZZt26:bimeib2) ([raw file](https://github.com/sillsdev/glyssen/blob/0c93581e5a98664688f3189700c5b57de0c9d49b/Glyssen/ScriptExporter.cs#L73)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Is this really a program error? Not assigning blocks feels like a user error that should be reported in production. (But maybe that happens elsewhere?)
</blockquote></details>

Thanks for forcing me to look at this again.
The user is warned when they go to export if all assignments are not complete.
But the programmer could do it anyway just like the user. So the Debug.Assert shouldn't be there.

---

*[Glyssen/Dialogs/ExportToRecordingToolDlg.cs, line 20 at r1](https://reviewable.io:443/reviews/sillsdev/glyssen/393#-KowdLwybE_4mpsDz5dN:-KoxHu1EePPkyOm3Gzz7:b4uvnpy) ([raw file](https://github.com/sillsdev/glyssen/blob/0c93581e5a98664688f3189700c5b57de0c9d49b/Glyssen/Dialogs/ExportToRecordingToolDlg.cs#L20)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Not sure what this does; looks like adding an event handler, but HandleStringsLocalized isn't a normal one of those. But if storing the function here may cause it to be called more than once (without updating m_lblDescription etc.), note that calling it a second time will fail, since the {0} in m_lblDescription.Text etc. will be wiped out by the first call.
</blockquote></details>

I'm not sure what you mean by it isn't a normal one of those.
This is the typical construct (AFAIK) for ensuring that if a user localizes via the L10NSharp dialog on the fly, the UI is immediately updated.
Ok, looking more, I guess you mean this isn't a typical EventHandler because of the signature?
For some reason, this implemented in L10NSharp as a delegate.

I did expect it to fail, too. But it doesn't. I guess I will have to figure out why. : )
Looked briefly. This delegate gets called twice, the first time with the {0}s already replaced, the second with what is needed to get everything correctly set in the UI language. Not going to look into more at this time...

---

*[Glyssen/Dialogs/ViewScriptDlg.cs, line 99 at r1](https://reviewable.io:443/reviews/sillsdev/glyssen/393#-KoweOIURjJXYzIRpqlF:-KoxOX0m_t9FO56S5nrx:bac4qol) ([raw file](https://github.com/sillsdev/glyssen/blob/0c93581e5a98664688f3189700c5b57de0c9d49b/Glyssen/Dialogs/ViewScriptDlg.cs#L99)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I have no idea why this is necessary, so a comment might be appropriate...also a 'try/finally'?
</blockquote></details>

I cleaned up this code. Thanks.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/glyssen/393)*

**Comment by JohnThomson** [comment]
:lgtm: with very minor and optional suggestions...no need for further review as far as I'm concerned.

---

Reviewed 9 of 9 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[Glyssen/ScriptExporter.cs, line 13 at r1](https://reviewable.io:443/reviews/sillsdev/glyssen/393#-Kow_B-TDWpiqTQkmsuk:-KpKrvrOniCOl0-XVSVU:b-d840oz) ([raw file](https://github.com/sillsdev/glyssen/blob/0c93581e5a98664688f3189700c5b57de0c9d49b/Glyssen/ScriptExporter.cs#L13)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Yes, I started to do that and push it all the way up. It became way too much for this change. I do have some work in progress in that direction I was hoping to do afterward, but, of course, I will never be able to prioritize it...
I suppose I could make use of the object here for now, and then it could be integrated in more piecemeal... I'll look into that. Thanks.
</blockquote></details>

I like what you've done. At least the code that has to know about the strange way the data is passed is all in one place. A brief comment explaining why the data comes this way rather than already in ExportBlocks (and any plans you weren't able to get to) might be helpful.

---

*[Glyssen/Dialogs/ExportToRecordingToolDlg.cs, line 20 at r1](https://reviewable.io:443/reviews/sillsdev/glyssen/393#-KowdLwybE_4mpsDz5dN:-KowdPyhkCP5M_Y9BcGq:bg7zqc2) ([raw file](https://github.com/sillsdev/glyssen/blob/0c93581e5a98664688f3189700c5b57de0c9d49b/Glyssen/Dialogs/ExportToRecordingToolDlg.cs#L20)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I'm not sure what you mean by it isn't a normal one of those.
This is the typical construct (AFAIK) for ensuring that if a user localizes via the L10NSharp dialog on the fly, the UI is immediately updated.
Ok, looking more, I guess you mean this isn't a typical EventHandler because of the signature?
For some reason, this implemented in L10NSharp as a delegate.

I did expect it to fail, too. But it doesn't. I guess I will have to figure out why. : )
Looked briefly. This delegate gets called twice, the first time with the {0}s already replaced, the second with what is needed to get everything correctly set in the UI language. Not going to look into more at this time...
</blockquote></details>

I suppose if it's being called by L10NSharp, it would be looking up a localization by ID each time, and getting a localized string that (hopefully) has any appropriate placeholders in it. And if this is the kind of delegate L10NSharp requires, clients are stuck with it. So I think things are fine.

---

*[GlyssenTests/ScriptExporterTests.cs, line 10 at r2](https://reviewable.io:443/reviews/sillsdev/glyssen/393#-KpKvg0so8BXBMLBn3Yh:-KpKvg0so8BXBMLBn3Yi:b-a72gm) ([raw file](https://github.com/sillsdev/glyssen/blob/877e276dc039702358215dc247302904d9e2d702/GlyssenTests/ScriptExporterTests.cs#L10)):*
> ```Smalltalk
> 	class ScriptExporterTests
> 	{
> 		private static readonly ProjectExporter.ExportBlock s_matBookTitle = new ProjectExporter.ExportBlock
> ```

I think I would have been inclined to use names with something like "Chapter0" rather than "BookTitle", since it's not immediately obvious that a book title goes in a chapter by itself, and the point is (I think) to test various aspects of the logic of books that do and don't have "0" chapters.

---

*[GlyssenTests/ScriptExporterTests.cs, line 88 at r2](https://reviewable.io:443/reviews/sillsdev/glyssen/393#-KpKwF0BaM2gjQ3a9uBV:-KpKwF0BaM2gjQ3a9uBW:bdpoyhe) ([raw file](https://github.com/sillsdev/glyssen/blob/877e276dc039702358215dc247302904d9e2d702/GlyssenTests/ScriptExporterTests.cs#L88)):*
> ```Smalltalk
> 			Assert.That(glyssenScript.Script.Books[1].Id, Is.EqualTo("REV"));
> 			Assert.That(glyssenScript.Script.Books[1].Chapters[0].Id, Is.EqualTo(1));
> 			Assert.That(glyssenScript.Script.Books[1].Chapters[0].Blocks[0].VernacularText.Text, Is.EqualTo("Dis book laan we bout de ting dem wa Jedus Christ show ta dem people wa da do God wok. God fus show Jedus dem ting yah, so dat Jedus kin mek dem wa da do e wok know dem ting wa gwine happen tareckly. Christ sen e angel ta John wa beena wok fa um, an e mek de angel show John dem ting yah. "));
> ```

Feels like we should have some asserts about Books[0], too.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/glyssen/393#-:-KpKwOeV8WqCLIm0uYoj:bxit96d)*

**Comment by andrew-polk** [comment]
Review status: 9 of 11 files reviewed at latest revision, 4 unresolved discussions.

---

*[Glyssen/ScriptExporter.cs, line 13 at r1](https://reviewable.io:443/reviews/sillsdev/glyssen/393#-Kow_B-TDWpiqTQkmsuk:-KpL16jAjI_PnSiuEzmV:b-896fix) ([raw file](https://github.com/sillsdev/glyssen/blob/0c93581e5a98664688f3189700c5b57de0c9d49b/Glyssen/ScriptExporter.cs#L13)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I like what you've done. At least the code that has to know about the strange way the data is passed is all in one place. A brief comment explaining why the data comes this way rather than already in ExportBlocks (and any plans you weren't able to get to) might be helpful.
</blockquote></details>

Done.

---

*[GlyssenTests/ScriptExporterTests.cs, line 10 at r2](https://reviewable.io:443/reviews/sillsdev/glyssen/393#-KpKvg0so8BXBMLBn3Yh:-KpL-LZQD_e3dekOtFWG:b-896fix) ([raw file](https://github.com/sillsdev/glyssen/blob/877e276dc039702358215dc247302904d9e2d702/GlyssenTests/ScriptExporterTests.cs#L10)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I think I would have been inclined to use names with something like "Chapter0" rather than "BookTitle", since it's not immediately obvious that a book title goes in a chapter by itself, and the point is (I think) to test various aspects of the logic of books that do and don't have "0" chapters.
</blockquote></details>

Done.

---

*[GlyssenTests/ScriptExporterTests.cs, line 88 at r2](https://reviewable.io:443/reviews/sillsdev/glyssen/393#-KpKwF0BaM2gjQ3a9uBV:-KpL-KD7TwQTCOxR-P1N:b-896fix) ([raw file](https://github.com/sillsdev/glyssen/blob/877e276dc039702358215dc247302904d9e2d702/GlyssenTests/ScriptExporterTests.cs#L88)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Feels like we should have some asserts about Books[0], too.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/glyssen/393)*

**Pull request merged**
