### PR TITLE
PG-1162: Processed OT Director's Guide versions 7-10

### PR DESCRIPTION
**Pull request by tombogle**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/glyssen/786)

### CODE REVIEW

**Review by andrew-polk — COMMENTED** [review]
> Reviewed 6 of 14 files at r1, 10 of 19 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/glyssen/786)* status: 12 of 25 files reviewed, 1 unresolved discussion (waiting on @andrew-polk and @tombogle)

___
*[DistFiles/localization/Glyssen.fr.xlf, line 1110 at r2](https://reviewable.io/reviews/sillsdev/glyssen/786#-MdNynoK1DdoNzrQZSQq:-MdNynoK1DdoNzrQZSQr:b-4x2zcu) ([raw file](https://github.com/sillsdev/glyssen/blob/0e1348e1428d2755990a3ce2b636fb73b3b93ebc/DistFiles/localization/Glyssen.fr.xlf#L1110)):*
> ```XML
>         <target xml:lang="fr" state="translated">Jérémie</target>
>       </trans-unit>
>       <trans-unit id="CharacterName.Jeremiah(Yahweh says)" sil:dynamic="true">
> ```

Most languages (besides en and es) lost a space before the parentheses.

**Review by andrew-polk — COMMENTED** [review]
> Reviewed 12 of 48 files at r3.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/glyssen/786)* status: 15 of 55 files reviewed, 1 unresolved discussion (waiting on @andrew-polk and @tombogle)

___
*[Reference Text Utility/RefTextUtilityForm.cs, line 35 at r3](https://reviewable.io/reviews/sillsdev/glyssen/786#-Mdxio3U6N71K-Rb_l1T:-Mdxio3U6N71K-Rb_l1U:bxojn1m) ([raw file](https://github.com/sillsdev/glyssen/blob/d41cdf4d1cb4e2d57eafcb5da1af3a1b28e4baee/Reference Text Utility/RefTextUtilityForm.cs#L35)):*
> ```
> Utlity
> ```
Utility

**Comment by tombogle** [comment]
___
*[Reference Text Utility/RefTextUtilityForm.cs, line 35 at r3](https://reviewable.io/reviews/sillsdev/glyssen/786#-Mdxio3U6N71K-Rb_l1T:-Me00xEV9H8YLkvSdTz7:b-896fix) ([raw file](https://github.com/sillsdev/glyssen/blob/d41cdf4d1cb4e2d57eafcb5da1af3a1b28e4baee/Reference Text Utility/RefTextUtilityForm.cs#L35)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> Utlity
> ```
Utility
</blockquote></details>

Done.

**Review by andrew-polk — COMMENTED** [review]
> Reviewed 5 of 8 files at r4.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/glyssen/786)* status: 18 of 58 files reviewed, 1 unresolved discussion (waiting on @andrew-polk and @tombogle)

___
*[RefTextDevUtilities/ReferenceTextData.cs, line 78 at r4](https://reviewable.io/reviews/sillsdev/glyssen/786#-Me10r1WC72RhRzqWM7E:-Me10r1X159ofK8h-Q1z:b5te420) ([raw file](https://github.com/sillsdev/glyssen/blob/189161b3a6f730df0da643403295aa11b615364d/RefTextDevUtilities/ReferenceTextData.cs#L78)):*
> ```
> CharacterId.EndsWith(")");
> ```
Feels fragile, but maybe the best you can do?

**Comment by tombogle** [comment]
___
*[DistFiles/localization/Glyssen.fr.xlf, line 1110 at r2](https://reviewable.io/reviews/sillsdev/glyssen/786#-MdNynoK1DdoNzrQZSQq:-Me16g-Z5qMKq1VlEhr4:b-886gsx) ([raw file](https://github.com/sillsdev/glyssen/blob/0e1348e1428d2755990a3ce2b636fb73b3b93ebc/DistFiles/localization/Glyssen.fr.xlf#L1110)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Most languages (besides en and es) lost a space before the parentheses.
</blockquote></details>

Fixed

**Comment by tombogle** [comment]
___
*[RefTextDevUtilities/ReferenceTextData.cs, line 78 at r4](https://reviewable.io/reviews/sillsdev/glyssen/786#-Me10r1WC72RhRzqWM7E:-Me16jqxE4B7QMsJXIS3:b-d9mvue) ([raw file](https://github.com/sillsdev/glyssen/blob/189161b3a6f730df0da643403295aa11b615364d/RefTextDevUtilities/ReferenceTextData.cs#L78)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> CharacterId.EndsWith(")");
> ```
Feels fragile, but maybe the best you can do?
</blockquote></details>

It is. I thought about a more complex regular expression, but that would also probably be fragile in the other direction. I'm basically relying on Diff to catch the problem when/if FCBH changes things.

**Comment by tombogle** [comment]
___
*[RefTextDevUtilities/ReferenceTextData.cs, line 78 at r4](https://reviewable.io/reviews/sillsdev/glyssen/786#-Me10r1WC72RhRzqWM7E:-Me172Zm2reXyJkacmQm:bxp1ryz) ([raw file](https://github.com/sillsdev/glyssen/blob/189161b3a6f730df0da643403295aa11b615364d/RefTextDevUtilities/ReferenceTextData.cs#L78)):*
<details><summary><i>Previously, tombogle (Tom Bogle) wrote…</i></summary><blockquote>

It is. I thought about a more complex regular expression, but that would also probably be fragile in the other direction. I'm basically relying on Diff to catch the problem when/if FCBH changes things.
</blockquote></details>

But it is worth a comment at least.

**Review by andrew-polk — COMMENTED** [review]
> Reviewed 1 of 18 files at r5.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/glyssen/786)* status: 17 of 59 files reviewed, 1 unresolved discussion (waiting on @andrew-polk and @tombogle)

___
*[RefTextDevUtilities/ReferenceTextData.cs, line 122 at r5](https://reviewable.io/reviews/sillsdev/glyssen/786#-Me2DLsOCHAgVus0RGAW:-Me2DLsOCHAgVus0RGAX:brwyfjy) ([raw file](https://github.com/sillsdev/glyssen/blob/3be17a10a2ec6d220c50fd4afbfcc40758373f47/RefTextDevUtilities/ReferenceTextData.cs#L122)):*
> ```Smalltalk
> 		}
> 
> 		private static string ConvertFcbhBookCodeToSilBookCode(string fcbhBookCode, out int bookNum)
> ```

This logic is already in ReferenceTextUtility.

**Comment by tombogle** [comment]
___
*[RefTextDevUtilities/ReferenceTextData.cs, line 122 at r5](https://reviewable.io/reviews/sillsdev/glyssen/786#-Me2DLsOCHAgVus0RGAW:-Me6EVXe2o07erx26EPu:b-1ee7g2) ([raw file](https://github.com/sillsdev/glyssen/blob/3be17a10a2ec6d220c50fd4afbfcc40758373f47/RefTextDevUtilities/ReferenceTextData.cs#L122)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

This logic is already in ReferenceTextUtility.
</blockquote></details>

There were two different methods being called at two different times. One had the NT books and the other had the OT books. I combined them and put them in ReferenceTextData. =

**Review by andrew-polk — COMMENTED** [review]
> Reviewed 1 of 18 files at r5.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/glyssen/786)* status: 18 of 59 files reviewed, all discussions resolved (waiting on @andrew-polk and @tombogle)

**Review by andrew-polk — COMMENTED** [review]
> Reviewed 2 of 27 files at r6.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/glyssen/786)* status: 18 of 59 files reviewed, all discussions resolved (waiting on @andrew-polk and @tombogle)

**Review by andrew-polk — APPROVED** [review]
I only gave a cursory glance at a handful of scripture (xml) files.
I scanned through CharacterDetail.
CharacterVerse is considered just one big change, so I don't see any way to review that. 

Let me know if there is something I should look at more closely.

> Reviewed 3 of 48 files at r3, 12 of 18 files at r5, 23 of 27 files at r6, 8 of 8 files at r7.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/glyssen/786#-:-Mf9rDvl8oiYAJVnsyvL:b-vrptrs)* status: all files reviewed, 1 unresolved discussion (waiting on @tombogle)

___
*[DistFiles/reference_texts/English/SNG.xml, line 447 at r7](https://reviewable.io/reviews/sillsdev/glyssen/786#-Mf9pl3T8X23kW9UaroR:-Mf9pl3U1lunOQ4T14kk:byh86sz) ([raw file](https://github.com/sillsdev/glyssen/blob/75112942fcff825650d39dfccfd14434c514b212/DistFiles/reference_texts/English/SNG.xml#L447)):*
> ```XML
>   <block style="p" chapter="7" initialStartVerse="11" characterId="narrator-SNG">
>     <verse num="11" />
>     <text>Come, my beloved! Let’s go out into the field. Let’s lodge in the villages.</text>
> ```

I don't understand why all these are narrator. But I know this is a complicated book and you've done some complicated things. So it probably ok since it isn't a regression. Just wanted to be sure you were aware.

**Comment by tombogle** [comment]
Probably the handful of code changes are the only things that merit scrutiny. The control file changes would be difficult to review. Very likely there are some things that are less than perfect, but those will probably have to be caught by real users who stumble over them.

**Comment by tombogle** [comment]
___
*[DistFiles/reference_texts/English/SNG.xml, line 447 at r7](https://reviewable.io/reviews/sillsdev/glyssen/786#-Mf9pl3T8X23kW9UaroR:-MfDT-eBBZi1WzVP4fiQ:b-w8bn2m) ([raw file](https://github.com/sillsdev/glyssen/blob/75112942fcff825650d39dfccfd14434c514b212/DistFiles/reference_texts/English/SNG.xml#L447)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I don't understand why all these are narrator. But I know this is a complicated book and you've done some complicated things. So it probably ok since it isn't a regression. Just wanted to be sure you were aware.
</blockquote></details>

Since SNG does not have any reporting clauses (in Hebrew) except for a small handful of places, it is rare that a translation will include quotes around the text pertaining to the different characters in the poetic drama. Therefore, most of the text comes through as narrator. The narrator-overrides file attempts to handle dicing up the poem to assign the various parts to the appropriate speakers.

**Pull request merged**
