### PR TITLE
Upgraded libpalaso DLLs and switched to SIL.DesktopAnalytics

### PR DESCRIPTION
**Pull request by tombogle**
Upgraded lots of other DLLs

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/glyssen/834)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 34 of 34 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/glyssen/834)* status: all files reviewed, 1 unresolved discussion (waiting on @tombogle)

___
*[`ControlDataIntegrityTests/ControlDataIntegrityTests.csproj` line 75 at r1](https://reviewable.io/reviews/sillsdev/glyssen/834#-N8jCE_U8Ffi2LYziCJY:-N8jCE_U8Ffi2LYziCJZ:b-ded0vv) ([raw file](https://github.com/sillsdev/glyssen/blob/f1bdaa81ff1c820a8c3bea8111d5656729c91900/ControlDataIntegrityTests/ControlDataIntegrityTests.csproj#L75)):*
> ```XML
>     <Reference Include="JetBrains.Annotations, Version=4242.42.42.42, Culture=neutral, PublicKeyToken=1010a0d8d6380325, processorArchitecture=MSIL">
>       <HintPath>..\packages\JetBrains.Annotations.2022.1.0\lib\net20\JetBrains.Annotations.dll</HintPath>
>     </Reference>
> ```

I thought I had fixed the various SIL packages to not bring this in by making it a private dep.
Maybe I missed one? Or something like ParatextData is not set up correctly?

I'm pretty sure it won't hurt anything to leave it as is, but I'm also pretty sure that changing deps should never bring in this package.

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/glyssen/834)* status: all files reviewed, 2 unresolved discussions (waiting on @tombogle)

___
*[`CHANGELOG.md` line 19 at r1](https://reviewable.io/reviews/sillsdev/glyssen/834#-N8jE7b_D8uG7jANBike:-N8jE7b_D8uG7jANBikf:bkh5duo) ([raw file](https://github.com/sillsdev/glyssen/blob/f1bdaa81ff1c820a8c3bea8111d5656729c91900/CHANGELOG.md#L19)):*
> ```Markdown
> ## [Unreleased]
> 
> ## [4.0.0] - 2022-08-05
> ```

I don't claim to understand gitversion and its interaction with the changelog, but I notice you added 4.0 here without any commit comment to change the version.

**Comment by tombogle** [comment]
*[`CHANGELOG.md` line 19 at r1](https://reviewable.io/reviews/sillsdev/glyssen/834#-N8jE7b_D8uG7jANBike:-N8xUsz46MfMI5it_Iiq:bg1knjg) ([raw file](https://github.com/sillsdev/glyssen/blob/f1bdaa81ff1c820a8c3bea8111d5656729c91900/CHANGELOG.md#L19)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I don't claim to understand gitversion and its interaction with the changelog, but I notice you added 4.0 here without any commit comment to change the version.
</blockquote></details>

Glyssen gets its version number using the GitVersion feature of retrieving it from the tag. So after mergin this, I will push up a v4.0.0 tag, and then kick off the release build. That said, it didn't get released last Friday, so now I need to update the date.

**Comment by tombogle** [comment]
*[`ControlDataIntegrityTests/ControlDataIntegrityTests.csproj` line 75 at r1](https://reviewable.io/reviews/sillsdev/glyssen/834#-N8jCE_U8Ffi2LYziCJY:-N8xX3KcEUDl8Vbbx7rX:b-xf12kp) ([raw file](https://github.com/sillsdev/glyssen/blob/f1bdaa81ff1c820a8c3bea8111d5656729c91900/ControlDataIntegrityTests/ControlDataIntegrityTests.csproj#L75)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I thought I had fixed the various SIL packages to not bring this in by making it a private dep.
Maybe I missed one? Or something like ParatextData is not set up correctly?

I'm pretty sure it won't hurt anything to leave it as is, but I'm also pretty sure that changing deps should never bring in this package.
</blockquote></details>

It's because of ParatextData. I'll see if they can change that.

**Comment by tombogle** [comment]
*[`ControlDataIntegrityTests/ControlDataIntegrityTests.csproj` line 75 at r1](https://reviewable.io/reviews/sillsdev/glyssen/834#-N8jCE_U8Ffi2LYziCJY:-N8z83QG4eTstmM9QcRD:b-5easjz) ([raw file](https://github.com/sillsdev/glyssen/blob/f1bdaa81ff1c820a8c3bea8111d5656729c91900/ControlDataIntegrityTests/ControlDataIntegrityTests.csproj#L75)):*
<details><summary><i>Previously, tombogle (Tom Bogle) wrote…</i></summary><blockquote>

It's because of ParatextData. I'll see if they can change that.
</blockquote></details>

Fixed it. Waiting for new version of PD...

**Review by andrew-polk — COMMENTED** [review]
> Reviewed 14 of 14 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/glyssen/834)* status: all files reviewed, 1 unresolved discussion (waiting on @tombogle)

___
*[`ControlDataIntegrityTests/ControlDataIntegrityTests.csproj` line 75 at r1](https://reviewable.io/reviews/sillsdev/glyssen/834#-N8jCE_U8Ffi2LYziCJY:-N991uo9E6WGsaYqnI0_:b193br0) ([raw file](https://github.com/sillsdev/glyssen/blob/f1bdaa81ff1c820a8c3bea8111d5656729c91900/ControlDataIntegrityTests/ControlDataIntegrityTests.csproj#L75)):*
<details><summary><i>Previously, tombogle (Tom Bogle) wrote…</i></summary><blockquote>

Fixed it. Waiting for new version of PD...
</blockquote></details>

Unfortunately, the JetBrains.Annotations package references remain.
But feel free to merge if you want.

**Comment by tombogle** [comment]
*[`ControlDataIntegrityTests/ControlDataIntegrityTests.csproj` line 75 at r1](https://reviewable.io/reviews/sillsdev/glyssen/834#-N8jCE_U8Ffi2LYziCJY:-N99TonHAgjrGvoE6q1_:bq8m9uv) ([raw file](https://github.com/sillsdev/glyssen/blob/f1bdaa81ff1c820a8c3bea8111d5656729c91900/ControlDataIntegrityTests/ControlDataIntegrityTests.csproj#L75)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Unfortunately, the JetBrains.Annotations package references remain.
But feel free to merge if you want.
</blockquote></details>

Gone now!

**Pull request merged**
