### PR TITLE
Issue PG-317: Single-voice should not change saved assignments

### PR DESCRIPTION
**Pull request by phillip-hopper**
Checking or unchecking "This book will be narrated" in character assignment should not change any assignments.

Update filters and percent completed.

[Review on Reviewable](https://reviewable.io/reviews/sillsdev/glyssen/80)

### CODE REVIEW

**Comment by andrew-polk** [comment]
Review status: 0 of 6 files reviewed at latest revision, 3 unresolved discussions.

---

*[Glyssen/Dialogs/AssignCharacterViewModel.cs, line 62 \[r1\]](https://reviewable.io:443/reviews/sillsdev/glyssen/80#-KBNf2JEF6Rb313Rvu0F:-KBNf2JFe2aC4KxeAPvA:1976960605) ([raw file](https://github.com/sillsdev/glyssen/blob/a0f445e64f06b9ea5997d37f779cfbb5eb3e1e24/Glyssen/Dialogs/AssignCharacterViewModel.cs#L62)):*
I think AreAllAssignmentsComplete should only be true if all books are complete.  So this logic looks incorrect to me.

---

*[Glyssen/Dialogs/BlockNavigatorViewModel.cs, line 612 \[r1\]](https://reviewable.io:443/reviews/sillsdev/glyssen/80#-KBNguo6zsqDBEw_urSt:-KBNguo6zsqDBEw_urSu:-146260171) ([raw file](https://github.com/sillsdev/glyssen/blob/a0f445e64f06b9ea5997d37f779cfbb5eb3e1e24/Glyssen/Dialogs/BlockNavigatorViewModel.cs#L612)):*
Some filters (at least All Scripture but perhaps others?) should still be relevant for single voice.

---

*[GlyssenTests/Dialogs/AssignCharacterViewModelTests.cs, line 381 \[r1\]](https://reviewable.io:443/reviews/sillsdev/glyssen/80#-KBNhayh_XXQyYSDSls3:-KBNhayh_XXQyYSDSls4:626950512) ([raw file](https://github.com/sillsdev/glyssen/blob/03bcbf8ba4946afb2a1edafcdc60560f99cbda40/GlyssenTests/Dialogs/AssignCharacterViewModelTests.cs#L381)):*
It looks like we are actually testing two different things in this test.  Perhaps we should leave the test for the "CurrentBlockIsUnchanged" part and just remove the check that blocks were assigned to narrator?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/sillsdev/glyssen/80)*

**Comment by phillip-hopper** [comment]
Review status: 0 of 6 files reviewed at latest revision, 3 unresolved discussions.

---

*[Glyssen/Dialogs/AssignCharacterViewModel.cs, line 62 \[r1\]](https://reviewable.io:443/reviews/sillsdev/glyssen/80#-KBNf2JEF6Rb313Rvu0F:-KBOCKuODE6s4yCDP-VL:-311297219) ([raw file](https://github.com/sillsdev/glyssen/blob/8f2768fc3e6b272823909068ba75849ca8a27366/Glyssen/Dialogs/AssignCharacterViewModel.cs#L62)):*
I reverted this change.

---

*[Glyssen/Dialogs/BlockNavigatorViewModel.cs, line 612 \[r1\]](https://reviewable.io:443/reviews/sillsdev/glyssen/80#-KBNguo6zsqDBEw_urSt:-KBhfpH_M1AVJlYemO7C:-499146009) ([raw file](https://github.com/sillsdev/glyssen/blob/8f2768fc3e6b272823909068ba75849ca8a27366/Glyssen/Dialogs/BlockNavigatorViewModel.cs#L612)):*
Done.

---

*[GlyssenTests/Dialogs/AssignCharacterViewModelTests.cs, line 381 \[r1\]](https://reviewable.io:443/reviews/sillsdev/glyssen/80#-KBNhayh_XXQyYSDSls3:-KBhfsXBnc6GlR3yqOAT:-499146009) ([raw file](https://github.com/sillsdev/glyssen/blob/a8c3f7df7fc9ecc52e88ae56c4e73db523f5abda/GlyssenTests/Dialogs/AssignCharacterViewModelTests.cs#L381)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/sillsdev/glyssen/80)*

**Comment by phillip-hopper** [comment]
Review status: 0 of 6 files reviewed at latest revision, 3 unresolved discussions.

---

*[Glyssen/Dialogs/AssignCharacterViewModel.cs, line 62 \[r1\]](https://reviewable.io:443/reviews/sillsdev/glyssen/80#-KBNf2JEF6Rb313Rvu0F:-KBiQqQKPYGWjKgdd12n:-499146009) ([raw file](https://github.com/sillsdev/glyssen/blob/8f2768fc3e6b272823909068ba75849ca8a27366/Glyssen/Dialogs/AssignCharacterViewModel.cs#L62)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/sillsdev/glyssen/80)*

**Comment by andrew-polk** [comment]
Reviewed 2 of 6 files at r1, 1 of 3 files at r3, 3 of 3 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/sillsdev/glyssen/80)*

**Pull request merged**
