### PR TITLE
PG-1058: Added support for Narration By Author with fewer narrators than authors.

### PR DESCRIPTION
**Pull request by tombogle**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/glyssen/408)

### CODE REVIEW

**Comment by tombogle** [comment]
WIP - Do not merge yet!

**Comment by tombogle** [comment]
This should be ready to review and merge. (Still might want to look at whether it makes sense to prevent choosing a single narrator when doing narration-by-author.)

**Comment by andrew-polk** [comment]
Reviewed 5 of 10 files at r1, 14 of 18 files at r2, 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[Glyssen/Rules/Proximity.cs, line 95 at r3](https://reviewable.io:443/reviews/sillsdev/glyssen/408#-KuzHBqGMQ3Ffr9OSTg2:-KuzHBqGMQ3Ffr9OSTg3:boei3c7) ([raw file](https://github.com/sillsdev/glyssen/blob/68ee923b0d4acce59fb464899d14fed8383759a7/Glyssen/Rules/Proximity.cs#L95)):*
> ```Smalltalk
> 				{
> 					var author = BiblicalAuthors.GetAuthorOfBook(book.BookId);
> 					if (author.CombineAuthorAndNarrator)
> ```

I still don't think this is sufficient. I think we have to know whether we are combining this author for this run.

I'll try to come up with something definitive.

---

*[GlyssenTests/Dialogs/CastSizePlanningViewModelTests.cs, line 39 at r3](https://reviewable.io:443/reviews/sillsdev/glyssen/408#-Kuz9eUfb7XWWqzkNgvl:-Kuz9eUfb7XWWqzkNgvm:b-8n530f) ([raw file](https://github.com/sillsdev/glyssen/blob/68ee923b0d4acce59fb464899d14fed8383759a7/GlyssenTests/Dialogs/CastSizePlanningViewModelTests.cs#L39)):*
> ```Smalltalk
> 			model.NarratorOption = NarratorsOption.Custom;
> 			model.MaleNarrators = 2;
> 			model.FemaleNarrators = 0;
> ```

All these tests setting model.FemaleNarrators then m_femaleNarratorsValue are pretty confusing. If we need to do that, some comments would be helpful.

---

*[GlyssenTests/Dialogs/CastSizePlanningViewModelTests.cs, line 75 at r3](https://reviewable.io:443/reviews/sillsdev/glyssen/408#-KuzA7DpmBSFb7nq-aGK:-KuzA7DpmBSFb7nq-aGL:b-v3d3zy) ([raw file](https://github.com/sillsdev/glyssen/blob/68ee923b0d4acce59fb464899d14fed8383759a7/GlyssenTests/Dialogs/CastSizePlanningViewModelTests.cs#L75)):*
> ```Smalltalk
> 			model.NarratorOption = NarratorsOption.NarrationByAuthor;
> 			Assert.AreEqual(2, m_maleNarratorsValue);
> 			Assert.AreEqual(0, m_femaleNarratorsValue);
> ```

Are all these female checks just to prove we didn't change anything?

---

*[GlyssenTests/Rules/TrialGroupConfigurationTests.cs, line 713 at r3](https://reviewable.io:443/reviews/sillsdev/glyssen/408#-KuzCuJyc38ft6WSCowE:-KuzCuJyc38ft6WSCowF:b-9bqh0v) ([raw file](https://github.com/sillsdev/glyssen/blob/68ee923b0d4acce59fb464899d14fed8383759a7/GlyssenTests/Rules/TrialGroupConfigurationTests.cs#L713)):*
> GeneratePossibilities_TwoNarrators_PaulByHimselfAndPeterNotInNarratorGroup

I think you've made the test more generic since you named it. (If I understand it correctly.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/glyssen/408)*

**Comment by andrew-polk** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/glyssen/408)*

**Comment by tombogle** [comment]
*[GlyssenTests/Dialogs/CastSizePlanningViewModelTests.cs, line 39 at r3](https://reviewable.io:443/reviews/sillsdev/glyssen/408#-Kuz9eUfb7XWWqzkNgvl:-Kv8GkG1rF_msM7zQjYt:bqccnke) ([raw file](https://github.com/sillsdev/glyssen/blob/68ee923b0d4acce59fb464899d14fed8383759a7/GlyssenTests/Dialogs/CastSizePlanningViewModelTests.cs#L39)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

All these tests setting model.FemaleNarrators then m_femaleNarratorsValue are pretty confusing. If we need to do that, some comments would be helpful.
</blockquote></details>

I pushed a change that I hope makes these tests more intelligible.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/glyssen/408)*

**Comment by tombogle** [comment]
*[GlyssenTests/Dialogs/CastSizePlanningViewModelTests.cs, line 75 at r3](https://reviewable.io:443/reviews/sillsdev/glyssen/408#-KuzA7DpmBSFb7nq-aGK:-Kv8Gxim8cFpqBvCkuSe:b-py1in7) ([raw file](https://github.com/sillsdev/glyssen/blob/68ee923b0d4acce59fb464899d14fed8383759a7/GlyssenTests/Dialogs/CastSizePlanningViewModelTests.cs#L75)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Are all these female checks just to prove we didn't change anything?
</blockquote></details>

The new version makes it more clear/explicit whether we're testing that a new value came through via an event or whether we're not expecting the event to fire at all.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/glyssen/408)*

**Comment by tombogle** [comment]
*[GlyssenTests/Rules/TrialGroupConfigurationTests.cs, line 713 at r3](https://reviewable.io:443/reviews/sillsdev/glyssen/408#-KuzCuJyc38ft6WSCowE:-Kv8IB5cx3hpbCLzwXXf:b-yisd1d) ([raw file](https://github.com/sillsdev/glyssen/blob/68ee923b0d4acce59fb464899d14fed8383759a7/GlyssenTests/Rules/TrialGroupConfigurationTests.cs#L713)):*
> GeneratePossibilities_TwoNarrators_PaulByHimselfAndPeterNotInNarratorGroup
Fixed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/glyssen/408)*

**Comment by andrew-polk** [comment]
Reviewed 2 of 2 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[Glyssen/Rules/Proximity.cs, line 95 at r3](https://reviewable.io:443/reviews/sillsdev/glyssen/408#-KuzHBqGMQ3Ffr9OSTg2:-Kv8Ws8OBs0e100mQLqi:bwqbrmg) ([raw file](https://github.com/sillsdev/glyssen/blob/68ee923b0d4acce59fb464899d14fed8383759a7/Glyssen/Rules/Proximity.cs#L95)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I still don't think this is sufficient. I think we have to know whether we are combining this author for this run.

I'll try to come up with something definitive.
</blockquote></details>

Don't hold this up on my part. If you think it is sufficient, go ahead and merge.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/glyssen/408)*

**Comment by tombogle** [comment]
*[Glyssen/Rules/Proximity.cs, line 95 at r3](https://reviewable.io:443/reviews/sillsdev/glyssen/408#-KuzHBqGMQ3Ffr9OSTg2:-KvAdLJ4jrWQDIAaXL5U:b48d9xw) ([raw file](https://github.com/sillsdev/glyssen/blob/68ee923b0d4acce59fb464899d14fed8383759a7/Glyssen/Rules/Proximity.cs#L95)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Don't hold this up on my part. If you think it is sufficient, go ahead and merge.
</blockquote></details>

I've improved it to address your concerns (I think)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/glyssen/408)*

**Comment by andrew-polk** [comment]
:lgtm:
I won't pretend to have understood all the changes, but you seem to have taken into account all the things we discussed previously.

---

Reviewed 3 of 3 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/glyssen/408#-:-KvDNPfdike99_2Z94T9:b-4y449z)*

**Comment by andrew-polk** [comment]
Reviewed 1 of 1 files at r8.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/glyssen/408)*

**Pull request merged**
