### PR TITLE
PG-771: Include copyright information about the reference text(s) in glyssenscript.

### PR DESCRIPTION
**Pull request by tombogle**
Also retrieve copyright information from the Paratext project settings.

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/glyssen/746)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/glyssen/746)* status: all files reviewed, 2 unresolved discussions (waiting on @tombogle)

___
*[GlyssenEngine/Export/ProjectExporter.cs, line 383 at r1](https://reviewable.io/reviews/sillsdev/glyssen/746#-MNeuoBe3QfJZ3iHatwR:-MNeuoBe3QfJZ3iHatwS:bpyx5ty) ([raw file](https://github.com/sillsdev/glyssen/blob/6bccac2726e5d90bdf678eb154ffd6ac5122ade7/GlyssenEngine/Export/ProjectExporter.cs#L383)):*
> ```Smalltalk
> 				if (primaryCopyrightInfo != null && primaryCopyrightInfo.Any())
> 				{
> 					primaryCopyrightInfo.Insert(0, $"{referenceText.LanguageName} reference text: {referenceText.Metadata.Identification?.Name}");
> ```

If you've made a conscious decision not to internationalize this string, probably worth a comment.
Or maybe we don't localize anything in the export currently?
___
*[GlyssenEngine/Export/ProjectExporter.cs, line 392 at r1](https://reviewable.io/reviews/sillsdev/glyssen/746#-MNevMpx5Q8xxIjhrd80:-MNevMpx5Q8xxIjhrd81:bnlp1u2) ([raw file](https://github.com/sillsdev/glyssen/blob/6bccac2726e5d90bdf678eb154ffd6ac5122ade7/GlyssenEngine/Export/ProjectExporter.cs#L392)):*
> ```Smalltalk
> 				xls.Workbook.Properties.Title = OutputName;
> 				var copyrightInfo = Project.Metadata.Copyright?.Statement?.InternalNodes?.Select(n => n.InnerText).ToList() ??
> 					new List<string>();
> ```

I find it awkward that all this inner knowledge is shared by this and this line above.
I guess maybe it isn't worth expanding the metadata class if that is in libpalaso, but do we have a derived class or some other place this knowledge can live?

**Comment by tombogle** [comment]
___
*[GlyssenEngine/Export/ProjectExporter.cs, line 383 at r1](https://reviewable.io/reviews/sillsdev/glyssen/746#-MNeuoBe3QfJZ3iHatwR:-MNi6MTsDriVgU6gdWYX:b-4l64fz) ([raw file](https://github.com/sillsdev/glyssen/blob/6bccac2726e5d90bdf678eb154ffd6ac5122ade7/GlyssenEngine/Export/ProjectExporter.cs#L383)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

If you've made a conscious decision not to internationalize this string, probably worth a comment.
Or maybe we don't localize anything in the export currently?
</blockquote></details>

It would have to be a dynamic string since it comes from the reference text, which could be one of ours (which are public domain anyway, so not a big deal) or one of the proprietary ones. Since its purpose is to protect the intellectual property in the reference text, it seems most fitting for it to be in the language of the reference text, but theoretically the reference text could already have it in multiple languages if so desired. For now at least the only actual use case I know of that matters is for the FCBH proprietary texts and since they all use the English UI, no one would ever see a localized version of it.

**Comment by tombogle** [comment]
___
*[GlyssenEngine/Export/ProjectExporter.cs, line 383 at r1](https://reviewable.io/reviews/sillsdev/glyssen/746#-MNeuoBe3QfJZ3iHatwR:-MNi8jsd4EpwgX3DT_sL:bm8t1om) ([raw file](https://github.com/sillsdev/glyssen/blob/6bccac2726e5d90bdf678eb154ffd6ac5122ade7/GlyssenEngine/Export/ProjectExporter.cs#L383)):*
<details><summary><i>Previously, tombogle (Tom Bogle) wrote…</i></summary><blockquote>

It would have to be a dynamic string since it comes from the reference text, which could be one of ours (which are public domain anyway, so not a big deal) or one of the proprietary ones. Since its purpose is to protect the intellectual property in the reference text, it seems most fitting for it to be in the language of the reference text, but theoretically the reference text could already have it in multiple languages if so desired. For now at least the only actual use case I know of that matters is for the FCBH proprietary texts and since they all use the English UI, no one would ever see a localized version of it.
</blockquote></details>

FWIW, we do include a column with localized character IDs in our export. (I'm pretty sure FCBH throws those away when they process the output using Nitro.)

**Comment by tombogle** [comment]
___
*[GlyssenEngine/Export/ProjectExporter.cs, line 392 at r1](https://reviewable.io/reviews/sillsdev/glyssen/746#-MNevMpx5Q8xxIjhrd80:-MNi9m8y4MbDtURvJ51n:b-sh7or3) ([raw file](https://github.com/sillsdev/glyssen/blob/6bccac2726e5d90bdf678eb154ffd6ac5122ade7/GlyssenEngine/Export/ProjectExporter.cs#L392)):*
> ```
> Project.Metadata.Copyright?.Statement?
> ```
I agree it is ugly and sub-optimal, but it would mean adding to the DblMetadataCopyright class in SIL.DblBundle. Giving it a constructor that takes a string and having it implement ToString (and/or having it implement an implicit or explicit conversion to/from string) would simplify Glyssen, so it might be worth the trouble. Even putting the implementation there would not guarantee that some future change to the DBL spec wouldn't break it, but at leats there would be one common place to fix it (though Glyssen might currently be the only application that cares about the internal representation.

**Review by andrew-polk — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/glyssen/746)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[GlyssenEngine/Export/ProjectExporter.cs, line 383 at r1](https://reviewable.io/reviews/sillsdev/glyssen/746#-MNeuoBe3QfJZ3iHatwR:-MNiPm3w4d_fcWJk0OUE:bux3wqk) ([raw file](https://github.com/sillsdev/glyssen/blob/6bccac2726e5d90bdf678eb154ffd6ac5122ade7/GlyssenEngine/Export/ProjectExporter.cs#L383)):*
<details><summary><i>Previously, tombogle (Tom Bogle) wrote…</i></summary><blockquote>

FWIW, we do include a column with localized character IDs in our export. (I'm pretty sure FCBH throws those away when they process the output using Nitro.)
</blockquote></details>

Ok, I agree it probably isn't worth localizing at this point. I'll leave to you if a comment is warranted.
___
*[GlyssenEngine/Export/ProjectExporter.cs, line 392 at r1](https://reviewable.io/reviews/sillsdev/glyssen/746#-MNevMpx5Q8xxIjhrd80:-MNiPrg46npLjRX_Z6I9:bd7c06i) ([raw file](https://github.com/sillsdev/glyssen/blob/6bccac2726e5d90bdf678eb154ffd6ac5122ade7/GlyssenEngine/Export/ProjectExporter.cs#L392)):*
<details><summary><i>Previously, tombogle (Tom Bogle) wrote…</i></summary><blockquote>

> ```
> Project.Metadata.Copyright?.Statement?
> ```
I agree it is ugly and sub-optimal, but it would mean adding to the DblMetadataCopyright class in SIL.DblBundle. Giving it a constructor that takes a string and having it implement ToString (and/or having it implement an implicit or explicit conversion to/from string) would simplify Glyssen, so it might be worth the trouble. Even putting the implementation there would not guarantee that some future change to the DBL spec wouldn't break it, but at leats there would be one common place to fix it (though Glyssen might currently be the only application that cares about the internal representation. 
</blockquote></details>

Ok, I'll leave it to you whether it is worth extracting.
The `.InternalNodes?.Select...` part is the one which seems worth abstracting.

**Comment by tombogle** [comment]
Now waiting on https://github.com/sillsdev/libpalaso/pull/1022

**Comment by tombogle** [comment]
___
*[GlyssenEngine/Export/ProjectExporter.cs, line 392 at r1](https://reviewable.io/reviews/sillsdev/glyssen/746#-MNevMpx5Q8xxIjhrd80:-MO8M_fQ8qK_J4rE-hxI:bb6un1j) ([raw file](https://github.com/sillsdev/glyssen/blob/cc32101864eb10fb4bb5398c84d95a64e0f3edb8/GlyssenEngine/Export/ProjectExporter.cs#L392)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Ok, I'll leave it to you whether it is worth extracting.
The `.InternalNodes?.Select...` part is the one which seems worth abstracting.
</blockquote></details>

Done

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 23 of 23 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/glyssen/746)* status: all files reviewed, 1 unresolved discussion (waiting on @tombogle)

___
*[GlyssenTests/GlyssenTests.csproj, line 116 at r2](https://reviewable.io/reviews/sillsdev/glyssen/746#-MO8NyyYCQ6yR1uV9UjO:-MO8NyyYCQ6yR1uV9UjP:b-hm94gj) ([raw file](https://github.com/sillsdev/glyssen/blob/ffa9552eea8a50cdfaa5868b4122666edb6ff7e0/GlyssenTests/GlyssenTests.csproj#L116)):*
> ```XML
>       <HintPath>..\packages\Markdig.Signed.0.22.0\lib\net452\Markdig.Signed.dll</HintPath>
>     </Reference>
>     <Reference Include="MarkdownDeep, Version=1.5.7366.28328, Culture=neutral, PublicKeyToken=a3790ba34fe8597c, processorArchitecture=MSIL">
> ```

Is MarkdownDeep still used?
Why did Markdig.Signed get added to GlyssenTests but not Glyssen?

**Comment by tombogle** [comment]
___
*[GlyssenTests/GlyssenTests.csproj, line 116 at r2](https://reviewable.io/reviews/sillsdev/glyssen/746#-MO8NyyYCQ6yR1uV9UjO:-MODC2KFBaRYvAH1uwJG:b-lzafo0) ([raw file](https://github.com/sillsdev/glyssen/blob/ffa9552eea8a50cdfaa5868b4122666edb6ff7e0/GlyssenTests/GlyssenTests.csproj#L116)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Is MarkdownDeep still used?
Why did Markdig.Signed get added to GlyssenTests but not Glyssen?
</blockquote></details>

I removed it and everything still builds, and the tests pass. Don't know how/why the package manager decided to add it to the tests and not to Glyssen itself. SIL.DblBundle.Tests depends on SIL.ReleaseTasks. SIL.ReleaseTasks, in turn, depends on MarkdownDeep (apparently to be able to stuff with changelog files), but it actually includes the DLL under tools/net461, so it does not depend on the package. There are several other projects in Glyssen, including Glyssen.csproj that depend directly on SIL.ReleaseTasks.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/glyssen/746)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by tombogle** [comment]
Since MarkdownDeep.dll was removed from the Installer this merits a bit of regression testing before releasing just to be sure.

**Pull request merged**
