### PR TITLE
PG-1360: Implemented "Synchronized scrolling" when user clicks in a reference text row

### PR DESCRIPTION
**Pull request by tombogle**
Added AssignCharacterViewModel.GetVerseRefForRow and code in AssignCharacterDlg to send the ref as a "Santa Fe" message so Paratext and other participating apps will go to the current reference when the user clicks in a reference text row.

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/glyssen/817)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/glyssen/817)* status: all files reviewed, 1 unresolved discussion (waiting on @tombogle)

___
*[CHANGELOG.md, line 20 at r1](https://reviewable.io/reviews/sillsdev/glyssen/817#-MxkpFm26Jrf1df-wuO8:-MxkpFm26Jrf1df-wuO9:b-jaoywz) ([raw file](https://github.com/sillsdev/glyssen/blob/b0d0e9e40c7d98df3477500b3d0de8b2a1d71b48/CHANGELOG.md#L20)):*
> ```Markdown
> ### Added
> 
> - AssignCharacterViewModel.GetVerseRefForRow
> ```

I think I would add the user-facing feature part of this (sync scrolling).

Otherwise, LGTM

**Comment by tombogle** [comment]
___
*[CHANGELOG.md, line 20 at r1](https://reviewable.io/reviews/sillsdev/glyssen/817#-MxkpFm26Jrf1df-wuO8:-Mxl5nu82UYgU2MLYejX:b-coft8y) ([raw file](https://github.com/sillsdev/glyssen/blob/b0d0e9e40c7d98df3477500b3d0de8b2a1d71b48/CHANGELOG.md#L20)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I think I would add the user-facing feature part of this (sync scrolling).

Otherwise, LGTM
</blockquote></details>

Good idea. I had only documented that change because it was the motivation for the semver:minor

**Comment by tombogle** [comment]
___
*[CHANGELOG.md, line 20 at r1](https://reviewable.io/reviews/sillsdev/glyssen/817#-MxkpFm26Jrf1df-wuO8:-Mxl6CDN8pIQCctnbKKr:b-y4dect) ([raw file](https://github.com/sillsdev/glyssen/blob/b0d0e9e40c7d98df3477500b3d0de8b2a1d71b48/CHANGELOG.md#L20)):*
<details><summary><i>Previously, tombogle (Tom Bogle) wrote…</i></summary><blockquote>

Good idea. I had only documented that change because it was the motivation for the semver:minor
</blockquote></details>

But I think the user-facing part belongs in the release notes.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/glyssen/817)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tombogle)

**Pull request merged**
