### PR TITLE
Updated copyright year and added acknowledgment to aboutBox.htm

### PR DESCRIPTION
**Pull request by tombogle**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/glyssen/767)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/glyssen/767)* status: all files reviewed, 4 unresolved discussions (waiting on @tombogle)

___
*[DistFiles/aboutBox.htm, line 18 at r1](https://reviewable.io/reviews/sillsdev/glyssen/767#-MTpd_V3E2X8VXBPJoYX:-MTpd_V3E2X8VXBPJoYY:b25p2ym) ([raw file](https://github.com/sillsdev/glyssen/blob/26848c7bdee794c4ec5e4c5e9f0317763dd3abb3/DistFiles/aboutBox.htm#L18)):*
> ```
> free open-source license
> ```
I don't think this is true anymore.
___
*[DistFiles/aboutBox.htm, line 19 at r1](https://reviewable.io/reviews/sillsdev/glyssen/767#-MTpdUvt6Xn5K0Gr4o3s:-MTpdUvt6Xn5K0Gr4o3t:bktvk3s) ([raw file](https://github.com/sillsdev/glyssen/blob/26848c7bdee794c4ec5e4c5e9f0317763dd3abb3/DistFiles/aboutBox.htm#L19)):*
> ```
> Microsoft, for inexpensive licenses of Visual Studio 2013.
> ```
This could use an update or probably just be removed.
___
*[DistFiles/aboutBox.htm, line 20 at r1](https://reviewable.io/reviews/sillsdev/glyssen/767#-MTpdmfX3WNZujOlPzji:-MTpdmfX3WNZujOlPzjj:b-cezza) ([raw file](https://github.com/sillsdev/glyssen/blob/26848c7bdee794c4ec5e4c5e9f0317763dd3abb3/DistFiles/aboutBox.htm#L20)):*
> ```
> free open-source license
> ```
Not sure if this is true anymore... not sure how to know.
___
*[DistFiles/aboutBox.htm, line 29 at r1](https://reviewable.io/reviews/sillsdev/glyssen/767#-MTpdvoc2OFCi8_zLDa6:-MTpdvoc2OFCi8_zLDa7:b-f8qd34) ([raw file](https://github.com/sillsdev/glyssen/blob/26848c7bdee794c4ec5e4c5e9f0317763dd3abb3/DistFiles/aboutBox.htm#L29)):*
> ```
> https://bitbucket.org/geckofx/geckofx
> ```
This has moved to https://hg.sr.ht/~hindlemail/geckofx

**Comment by tombogle** [comment]
___
*[DistFiles/aboutBox.htm, line 20 at r1](https://reviewable.io/reviews/sillsdev/glyssen/767#-MTpdmfX3WNZujOlPzji:-MTqIyi4E3koXFewTQ_c:b-ss463x) ([raw file](https://github.com/sillsdev/glyssen/blob/26848c7bdee794c4ec5e4c5e9f0317763dd3abb3/DistFiles/aboutBox.htm#L20)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> free open-source license
> ```
Not sure if this is true anymore... not sure how to know.
</blockquote></details>

From MikeB: 
We do have community licenses for Atlassian but I think it is more so because of our non-profit status than our open-source projects since not all our projects are open source.  We use the server products of Atlassian so we do not pay them, but we are paying for Amazon web hosting space.

**Review by tombogle — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/glyssen/767)* status: 1 of 2 files reviewed, 4 unresolved discussions (waiting on @andrew-polk)

___
*[DistFiles/aboutBox.htm, line 18 at r1](https://reviewable.io/reviews/sillsdev/glyssen/767#-MTpd_V3E2X8VXBPJoYX:-MTuUJBe1QNg3WE-qrjL:b-896fix) ([raw file](https://github.com/sillsdev/glyssen/blob/26848c7bdee794c4ec5e4c5e9f0317763dd3abb3/DistFiles/aboutBox.htm#L18)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> free open-source license
> ```
I don't think this is true anymore.
</blockquote></details>

Done.
___
*[DistFiles/aboutBox.htm, line 19 at r1](https://reviewable.io/reviews/sillsdev/glyssen/767#-MTpdUvt6Xn5K0Gr4o3s:-MTuUJTs76JwGoiPlXaN:b-896fix) ([raw file](https://github.com/sillsdev/glyssen/blob/26848c7bdee794c4ec5e4c5e9f0317763dd3abb3/DistFiles/aboutBox.htm#L19)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> Microsoft, for inexpensive licenses of Visual Studio 2013.
> ```
This could use an update or probably just be removed.
</blockquote></details>

Done.
___
*[DistFiles/aboutBox.htm, line 29 at r1](https://reviewable.io/reviews/sillsdev/glyssen/767#-MTpdvoc2OFCi8_zLDa6:-MTuUvyU7_d_xRN4E6wU:b-896fix) ([raw file](https://github.com/sillsdev/glyssen/blob/26848c7bdee794c4ec5e4c5e9f0317763dd3abb3/DistFiles/aboutBox.htm#L29)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> https://bitbucket.org/geckofx/geckofx
> ```
This has moved to https://hg.sr.ht/~hindlemail/geckofx
</blockquote></details>

Done.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/glyssen/767)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
