### PR TITLE
Add the View Script dialog

### PR DESCRIPTION
**Pull request by phillip-hopper**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/glyssen/99)

### CODE REVIEW

**Comment by andrew-polk** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[Glyssen/MainForm.cs, line 668 \[r1\]](https://reviewable.io:443/reviews/sillsdev/glyssen/99#-KDZWWUvIXgb1bVUqclS:-KDZWWUvIXgb1bVUqclT:-1720862199) ([raw file](https://github.com/sillsdev/glyssen/blob/969906d7295db182071e7fbe32b1dc54fc5a28a0/Glyssen/MainForm.cs#L668)):*
This needs to be modified now. But I can do it since I implemented this just today.

---

*[Glyssen/Dialogs/ViewScriptDlg.cs, line 29 \[r1\]](https://reviewable.io:443/reviews/sillsdev/glyssen/99#-KDZVCxo3hm4LBLhOmPI:-KDZVCxp9m5RfprIEjv5:-25499796) ([raw file](https://github.com/sillsdev/glyssen/blob/969906d7295db182071e7fbe32b1dc54fc5a28a0/Glyssen/Dialogs/ViewScriptDlg.cs#L29)):*
What's the reason for setting the dialog result here?

---

*[Glyssen/Dialogs/ViewScriptDlg.cs, line 56 \[r1\]](https://reviewable.io:443/reviews/sillsdev/glyssen/99#-KDZXc73U4qve3hf5glU:-KDZXc73U4qve3hf5glV:1858604720) ([raw file](https://github.com/sillsdev/glyssen/blob/969906d7295db182071e7fbe32b1dc54fc5a28a0/Glyssen/Dialogs/ViewScriptDlg.cs#L56)):*
From running the code locally, this appears to set the temp file location as the default location (shown the next time a user goes into the Export dialog).

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/sillsdev/glyssen/99)*

**Comment by phillip-hopper** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[Glyssen/Dialogs/ViewScriptDlg.cs, line 29 \[r1\]](https://reviewable.io:443/reviews/sillsdev/glyssen/99#-KDZVCxo3hm4LBLhOmPI:-KDZdEvbBr9HjspomXAH:375193432) ([raw file](https://github.com/sillsdev/glyssen/blob/969906d7295db182071e7fbe32b1dc54fc5a28a0/Glyssen/Dialogs/ViewScriptDlg.cs#L29)):*
To close the "View Script" dialog after they have exported.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/sillsdev/glyssen/99)*

**Comment by andrew-polk** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[Glyssen/MainForm.cs, line 668 \[r1\]](https://reviewable.io:443/reviews/sillsdev/glyssen/99#-KDZWWUvIXgb1bVUqclS:-KDZkvRJOz6qlmg2T0y0:324219086) ([raw file](https://github.com/sillsdev/glyssen/blob/969906d7295db182071e7fbe32b1dc54fc5a28a0/Glyssen/MainForm.cs#L668)):*
Looks like you did it. Thanks.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/sillsdev/glyssen/99)*

**Comment by phillip-hopper** [comment]
Review status: 1 of 8 files reviewed at latest revision, 2 unresolved discussions.

---

*[Glyssen/MainForm.cs, line 668 \[r1\]](https://reviewable.io:443/reviews/sillsdev/glyssen/99#-KDZWWUvIXgb1bVUqclS:-KDZjGzyz7RcmBvnt4sT:-499146009) ([raw file](https://github.com/sillsdev/glyssen/blob/969906d7295db182071e7fbe32b1dc54fc5a28a0/Glyssen/MainForm.cs#L668)):*
Done.

---

*[Glyssen/Dialogs/ViewScriptDlg.cs, line 56 \[r1\]](https://reviewable.io:443/reviews/sillsdev/glyssen/99#-KDZXc73U4qve3hf5glU:-KDZjJ5FQet2pJFFezh6:-499146009) ([raw file](https://github.com/sillsdev/glyssen/blob/969906d7295db182071e7fbe32b1dc54fc5a28a0/Glyssen/Dialogs/ViewScriptDlg.cs#L56)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/sillsdev/glyssen/99)*

**Comment by andrew-polk** [comment]
:lgtm:

---

Reviewed 7 of 7 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/sillsdev/glyssen/99#-:-KDZzKRC795TYpaJKj1f:1417088721)*

**Pull request merged**
