### PR TITLE
Prevent Sparkle Updater from relaunching Glyssen after install

### PR DESCRIPTION
**Pull request by tombogle**
because Installer already does this and it results in the two Glyssen processes detecting each other and killing themselves.
Fixed minor internationalization problem.
Minor refactoring/code cleanup.

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/glyssen/806)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
I'm not seeing anything here which would address sparkle or installation, etc.
I'm also not seeing, "Fixed minor internationalization problem."
Maybe some changes are missing??

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/glyssen/806#-:-MojhiMr9AmuTgyCMEvJ:b-mdxnk0)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tombogle)

**Comment by tombogle** [comment]
Oops. Just added the missing file. Thanks for catching that.

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/glyssen/806)* status: all files reviewed, 1 unresolved discussion (waiting on @tombogle)

___
*[Glyssen/MainForm.cs, line 1455 at r2](https://reviewable.io/reviews/sillsdev/glyssen/806#-Monn22JBvS1GLb76kBC:-Monn22JBvS1GLb76kBD:b-7hku0) ([raw file](https://github.com/sillsdev/glyssen/blob/e17f576c72b35c6413e6c1b59b5d7a764807cce4/Glyssen/MainForm.cs#L1455)):*
> ```Smalltalk
> 				ofd.Filter = Format("{0} ({1})|{1}|{2} ({3})|{3}",
> 					LocalizationManager.GetString("DialogBoxes.ImportDlg.GlyssenSharesFileTypeLabel", "Glyssen shares"), "*" + kShareFileExtension,
> 					LocalizationManager.GetString("DialogBoxes.FileDlg.AllFilesLabel", "All Files"), "*.*");
> ```

These two l10n strings--especially the first--are going to benefit from a comment, methinks.
I suppose you already considered not letting translators change "Glyssen"?

**Comment by tombogle** [comment]
___
*[Glyssen/MainForm.cs, line 1455 at r2](https://reviewable.io/reviews/sillsdev/glyssen/806#-Monn22JBvS1GLb76kBC:-MonvQZy5PHUvYuUykyk:b42y1he) ([raw file](https://github.com/sillsdev/glyssen/blob/e17f576c72b35c6413e6c1b59b5d7a764807cce4/Glyssen/MainForm.cs#L1455)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

These two l10n strings--especially the first--are going to benefit from a comment, methinks.
I suppose you already considered not letting translators change "Glyssen"?
</blockquote></details>

I did consider that, but I was afraid that it might make it more confusing to translate and I figured there's a decent chance some localizations would want to translate it without the word "Glyssen" at all. Of course, that's still possible by just omitting the {0}, but Crowdin complains about it.

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/glyssen/806)* status: all files reviewed, 1 unresolved discussion (waiting on @tombogle)

___
*[Glyssen/MainForm.cs, line 1455 at r2](https://reviewable.io/reviews/sillsdev/glyssen/806#-Monn22JBvS1GLb76kBC:-Moo0SaXA-8k30sGhk4h:b8dx61p) ([raw file](https://github.com/sillsdev/glyssen/blob/e17f576c72b35c6413e6c1b59b5d7a764807cce4/Glyssen/MainForm.cs#L1455)):*
<details><summary><i>Previously, tombogle (Tom Bogle) wrote…</i></summary><blockquote>

I did consider that, but I was afraid that it might make it more confusing to translate and I figured there's a decent chance some localizations would want to translate it without the word "Glyssen" at all. Of course, that's still possible by just omitting the {0}, but Crowdin complains about it.
</blockquote></details>

Sorry; I put two thoughts in one comment. And then you only responded to the second.

The first thought is that I think translators will benefit from a comment on the string(s) indicating more about the context.

**Comment by tombogle** [comment]
___
*[Glyssen/MainForm.cs, line 1455 at r2](https://reviewable.io/reviews/sillsdev/glyssen/806#-Monn22JBvS1GLb76kBC:-MooJByI7yCDRvh6QXi2:bnx43h3) ([raw file](https://github.com/sillsdev/glyssen/blob/e17f576c72b35c6413e6c1b59b5d7a764807cce4/Glyssen/MainForm.cs#L1455)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Sorry; I put two thoughts in one comment. And then you only responded to the second.

The first thought is that I think translators will benefit from a comment on the string(s) indicating more about the context.
</blockquote></details>

I saw the first one. Working on it...

**Review by andrew-polk — COMMENTED** [review]
Looks like some extra changes got in this time...

> Reviewed 5 of 10 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/glyssen/806#-:-Mot-lVW5ZXxvxurPtNY:b-v0z5jv)* status: 7 of 12 files reviewed, all discussions resolved (waiting on @tombogle)

___
*[Glyssen/MainForm.cs, line 1455 at r2](https://reviewable.io/reviews/sillsdev/glyssen/806#-Monn22JBvS1GLb76kBC:-Mot-_cEDB_2Es53gg0T:bvowwmc) ([raw file](https://github.com/sillsdev/glyssen/blob/e17f576c72b35c6413e6c1b59b5d7a764807cce4/Glyssen/MainForm.cs#L1455)):*
<details><summary><i>Previously, tombogle (Tom Bogle) wrote…</i></summary><blockquote>

I saw the first one. Working on it...
</blockquote></details>

Thanks. Sorry; I didn't realize it was an existing string.

**Comment by tombogle** [comment]
True. I usually like to rebuild the xlf file when I add a localizable string to make sure everything is correct with the plumbing. I noticed some (unrelated) things weren't quite as I expected and in the process of exploring to get a grasp on what was happening, I fixed a few things.

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 5 of 10 files at r3.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/glyssen/806)* status: all files reviewed, 2 unresolved discussions (waiting on @tombogle)

___
*[DistFiles/localization/Glyssen.en.xlf, line 5932 at r3](https://reviewable.io/reviews/sillsdev/glyssen/806#-Mot59UaDxqf8q0y-87U:-Mot59UaDxqf8q0y-87V:bqnkuag) ([raw file](https://github.com/sillsdev/glyssen/blob/459f561d007cf3d6457d8846b022a96795dfc5ed/DistFiles/localization/Glyssen.en.xlf#L5932)):*
> ```
> target
> ```
Shouldn't be a target element in Glyssen.en.xlf
___
*[DistFiles/localization/Glyssen.en.xlf, line 5937 at r3](https://reviewable.io/reviews/sillsdev/glyssen/806#-Mot5HjVB9XVrM8YxWs2:-Mot5HjVB9XVrM8YxWs3:b-o33m1d) ([raw file](https://github.com/sillsdev/glyssen/blob/459f561d007cf3d6457d8846b022a96795dfc5ed/DistFiles/localization/Glyssen.en.xlf#L5937)):*
> ```
> 	  	···
> ```
In case you care, there is extra whitespace here and about 40-50 lines down on "Short name"

**Review by tombogle — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/glyssen/806)* status: 11 of 12 files reviewed, 2 unresolved discussions (waiting on @andrew-polk)

___
*[DistFiles/localization/Glyssen.en.xlf, line 5932 at r3](https://reviewable.io/reviews/sillsdev/glyssen/806#-Mot59UaDxqf8q0y-87U:-MouZFfUB7X7-QMwzffN:b7fidvz) ([raw file](https://github.com/sillsdev/glyssen/blob/459f561d007cf3d6457d8846b022a96795dfc5ed/DistFiles/localization/Glyssen.en.xlf#L5932)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> target
> ```
Shouldn't be a target element in Glyssen.en.xlf
</blockquote></details>

Yeah, I caught that today (while working on a different branch)
___
*[DistFiles/localization/Glyssen.en.xlf, line 5937 at r3](https://reviewable.io/reviews/sillsdev/glyssen/806#-Mot5HjVB9XVrM8YxWs2:-MouZnrUE1drbEMCN6ec:b-886gsx) ([raw file](https://github.com/sillsdev/glyssen/blob/459f561d007cf3d6457d8846b022a96795dfc5ed/DistFiles/localization/Glyssen.en.xlf#L5937)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> 	  	···
> ```
In case you care, there is extra whitespace here and about 40-50 lines down on "Short name"
</blockquote></details>

Fixed

**Review by andrew-polk — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/glyssen/806)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tombogle)

**Pull request merged**
